### ISSUE TITLE
Symbol is undefined in IE 11

### ISSUE THREAD

**Issue by george-dotdev** [Wikiki/bulma-calendar#109]
Babel doesn't polyfill Symbol because it is a feature not a syntax

**Comment by Wikiki** [comment]
Thanks for the notice I'll have a look at it

**Comment by Wikiki** [comment]
Fixed: https://github.com/Wikiki/bulma-calendar/commit/21e5d111ba045f3cf57b12378ead36618a1b2d92

**Comment by emkajeej** [comment]
excellent. can we expect this fix in the bulma-extensions npm package?
