### ISSUE TITLE
VueJs and input value

### ISSUE THREAD

**Issue by gsacre** [Wikiki/bulma-calendar#110]
Hello,

Thanks for this great addon!
I'm trying to use it with VueJS and I can't seem to set the 'value' for the input to something that is coming from PHP (in my case).
So here is what I'm trying to achieve:

- I pick some data from DB and display the page
- If there's something in the date field, I'd like to display it
- If the user wants to update that data, they should click on it and select a new date

Here is the code that I have (it's using the blade templating engine from Laravel):

```php
<date2 class="input{{ $errors->has('planned_start_date') ? ' is-danger' : '' }}" name="planned_start_date" value="{{ date('d-M-Y', strtotime($planned_start_date)) }}"/>
```
This is simply not working. When I inspect the DOM, here is what I have:

```html
<input type="text" name="planned_start_date" value="19-Oct-2018" class="input">
```

However, nothing is printed in the `input` field.

I tried to play a bit with the VueJS side of things and here's my (naive) Vue code:

```javascript
<template>
<input type="date" ref="calendarTrigger" :value="value">
</template>

<script>
  export default {
    props : ['value'],
    data () {
        return {
            mydate: (this.value.length > 0) ? this.value : new Date(),
        }
    },
    mounted() {
    	const calendar = bulmaCalendar.attach(this.$refs.calendarTrigger, {
				startDate: this.mydate,
				dateFormat: 'DD-MMM-YYYY',
				isRange: false,
				weekStart: 1,
				showHeader: false,
			})[0];
	},
    computed: {
        niceDate() {
            if (this.mydate) {
                return this.mydate
            }
        }
    },
  }

</script>
```
Here is the resulted HTML code:

```html
<input type="text" name="planned_start_date" class="input">
```

I tried to play with "nextTick" and I've added the following in my `mounted()` function:

```javascript
this.$nextTick(() => {
 	this.value = this.mydate;
})
```

This did nothing to improve.
Out of desperation, I tried to enter a fixed string in the "nextTick" and that did the trick as long as `this.value` was different from `this.mydate`.

I'm sure I'm missing something on the VueJS side (I'm pretty new at this) but then why simply putting the `value` tag in HTML doesn't work either?

Thanks in advance fo your help!

**Comment by ony3000** [comment]
The official document used date type input as a base structure.
But according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Value), date value must format `YYYY-MM-DD` regardless of displayed format.
So the simplest way to print `19-Oct-2018` properly, change the input type to text.

**Comment by gsacre** [comment]
You're my hero!
I can't believe this was that simple, thank you so much!
