### ISSUE TITLE
calendar-weekdays with dd option

### ISSUE THREAD

**Issue by 3tlam** [Wikiki/bulma-calendar#112]
Heya

I could not find it in the documentation, but I saw that for each locale in there are several types of weekdays (`dddd`, `ddd`, `dd`), but now I don't know how to change it?

In German you usually use two letters for the weekdays (Mo, Di, Mi, ..) 

I am guessing there should be an option somewhere?

Thanks!
Malte

**Comment by 3tlam** [comment]
Couldn't find the option, nor got an answer, so I hacked it into the script:
inside the `_build()` function, change `return __WEBPACK_IMPORTED_MODULE_2_date_fns__["format"](__WEBPACK_IMPORTED_MODULE_2_date_fns__["addDays"](d, i + _this3.options.weekStart), 'dd', {` (at the end) to the preferred weekday

**Comment by Wikiki** [comment]
Hi,

use the dateFormat option. There is no automatic format set based on the language.

Regards

**Comment by 3tlam** [comment]
No, this does not solve the problem!
I am talking about the weekdays on the top. They are - as far as I have been able to figure out - not influenced by `dateFormat`
![image](https://user-images.githubusercontent.com/6067365/48125441-fb058600-e27e-11e8-917f-d9af7bfc5b61.png)

**Comment by Wikiki** [comment]
I didn't understood. Sorry.
You're right it's not influenced by dateFormat option.
There is no option to change the format yet.
I'll add it in a next release.
