### ISSUE TITLE
Not picking up custom styles.

### ISSUE THREAD

**Issue by poojaagarwal1009** [Wikiki/bulma-calendar#113]
Hi, 

my bulma component is working(horrah!!!) with the following setting
in my **calendar.component.scss** file 
@import "~bulma-calendar/dist/css/bulma-calendar.min.css";
in **my calendar.component.js** file 
import bulmaCalendar from 'bulma-calendar/dist/js/bulma-calendar';

However, i have custom styling, so now instead adding css file in my component i'm adding it my **custom-bulma.scss** file like below
    $primary: blue;
    // Import the rest of Bulma
    @import "~bulma";
    @import "~bulma-calendar/src/sass/index";
( as per documentation which says "Depending on your need your can use either pre-compiled files from dist directory or sources from src directory.")

and custom-bulma is being imported in **index.scss** which in turn being used in main html file 
but this doesnt work. This is how my screen looks like
![image](https://user-images.githubusercontent.com/14246787/47199371-002c8f00-d3bd-11e8-8a1b-490f09c41558.png)

what m i doing wrong? dont know where the problem is, is it package.json, webpack.config.js or
do i have to change the javascript import too, if so then where. I'm using ES6.
any help would be appreciated.

Thanks for the great library!

**Comment by Kibouo** [comment]
Webpack should be telling you what went wrong. Can you link to a copy of the log?

**Comment by poojaagarwal1009** [comment]
i dont see any error, still would attach the screenshot, to make sure i'm not missing anything 
![image](https://user-images.githubusercontent.com/14246787/47248511-9cef3b00-d456-11e8-8fb6-9353602d7825.png)
![untitled](https://user-images.githubusercontent.com/14246787/47248640-754ca280-d457-11e8-9712-72db26283f58.png)

**Comment by poojaagarwal1009** [comment]
Hi, found the problem.
We define custom styles based on a custom attribute which we add by creating a ThemeWrapper around all elements.

Something like this

```
<div id="theme-wrapper" data-theme="mycustomtheme">
</div>

```
Also we append the custom data attribute in our custom Sass files as follows

```
@each $brandKey, $brandVars in $themes {
  [data-theme="#{$brandKey}"] {

    // Set your own initial variables
    $primary: map-get($brandVars, primaryColour);

    // Set the derived variables

    // Setup your Custom Colors

    // Add new color variables to the color map.
    @import "~bulma/sass/utilities/derived-variables.sass";

    // Import the rest of Bulma
    @import "~bulma";
    @import '~bulma-badge';
    @import '~bulma-tooltip';
    @import "~bulma-steps-component/bulma-steps";
    @import "~bulma-calendar/src/sass/index.scss";

    .button.is-primary[disabled] {
      background-color: $colour-dark-gray;
    }
  }
}

```
The problem is that the bulma-calendar creates the datePicker outside the root element. How can I add a wrapper around it?

![image](https://user-images.githubusercontent.com/14246787/47255375-f0e03b00-d4bb-11e8-9b82-e4b4483a50cc.png)

**Comment by Wikiki** [comment]
Hi,

the next release will fix the place where the component is added into the DOM to put it just after the element.

regards
