### ISSUE TITLE
Semicolon doesn't compile

### ISSUE THREAD

**Issue by ardeay** [Wikiki/bulma-calendar#115]
https://github.com/Wikiki/bulma-calendar/blob/8b27c264860e9b5ff61140cf31db92b72df3c1a0/src/sass/index.sass#L210

**Comment by 3tlam** [comment]
The error is the line before: it is missing a semicolon
`height: 100%`

**Comment by 3tlam** [comment]
You are right - my mistake!

**Comment by ardeay** [comment]
👍

**Comment by kobadg** [comment]
This issue still exists. Same line, same error.
