### ISSUE TITLE
Calendar dateformat or parse option when reading dates

### ISSUE THREAD

**Issue by fredericcormier** [Wikiki/bulma-calendar#119]
The dateformat option only works when retreiving a date from the calendar.
It does not work when setting the value of the input field.
I get this error

   ` The specified value "22-11-2018" does not conform to the required format, "yyyy-MM-dd"`

if I change the date to 2018-11-22 it works and shows in the input field

**Comment by ony3000** [comment]
Can you see #110? I think this issue can be solved in the same way.
