### ISSUE TITLE
Fails to work in Bulma Modal

### ISSUE THREAD

**Issue by matijakevic** [Wikiki/bulma-calendar#12]
If Date Picker input is placed inside Bulma Modal, clicking on the input causes calendar to show up behind the modal making user unable to input the date.

**Comment by Wikiki** [comment]
Hi,

can you please add screenshot or Codepen ?

regards

**Comment by Wikiki** [comment]
Fixed

**Comment by matthewblott** [comment]
I've just come across this issue, surprised to discover it's fixed. Am I doing something wrong? I have a calendar inside a modal. Works fine outside it but inside the modal I have the issue described above.

**Comment by affanabiyyu** [comment]
It's not working.
https://imgur.com/a/aBYkXgU

**Comment by Bismarck-GM** [comment]
![image](https://user-images.githubusercontent.com/43770133/99882827-fca20c80-2c01-11eb-9756-821ae1f2ead5.png)


Similar issue, but, having the Calendar inside a Bulma modal makes it always being displayed and no way to close it.

**Comment by dhruvindsd-dev** [comment]
> ![image](https://user-images.githubusercontent.com/43770133/99882827-fca20c80-2c01-11eb-9756-821ae1f2ead5.png)
> 
> Similar issue, but, having the Calendar inside a Bulma modal makes it always being displayed and no way to close it.

I'm facing a very similar issue, did you find any workarounds?

**Comment by michael-hack** [comment]
Should be fixed, that happen due to a attriute set for the modal class. But I see concerns because of the size and the unfolding behavior and would only use the inline or dialog variant in modals.

Please give me feedback...

**Comment by Bismarck-GM** [comment]
@dhruvindsd-dev sorry for the late response. I ended up just using the full calendar and somewhat patched what I had. A long time ago, don't remember it well, you can check it here https://github.com/Bismarck-GM/ToDoList-js

Thanks @michael-hack surely I'll come back to the project and try it at some point. Will give feedback if I find any issues.
