### ISSUE TITLE
date:selected event firing multiple times

### ISSUE THREAD

**Issue by zez9787** [Wikiki/bulma-calendar#122]
When listening for the ```"date:selected"``` event it will fire anytime the public event ```this.value()``` is called.

Is that by design or is it a possible bug? I noticed it because anytime you change the date on a calendar the ```"date:selected"``` event was firing twice. I ended up listening to the ```hide``` event and that accomplished what I needed but it may not work for everyone.

**Comment by buildscientist** [comment]
+1 for this issue. Relying on the hide event doesn't work when the displayMode is set to inline because the calendar isn't being hidden.

**Comment by alvaaz** [comment]
It seems to be a bug

**Comment by tangnv** [comment]
@zez9787 @buildscientist @alvaaz. For now they have 2 issues:
- Fire `date:selected` event 2 times
- Call `value()` will fire `date:selected` also

In their code, they emit `date:selected` event when we call `value()` function, i'm not sure why. To resolve it I copy their code and remove emit event to another function called `currentValue()`.
For the first issue, they call `value()` 2 times in `datePickerChange`.

Let use this file for temporary: https://gist.githubusercontent.com/tangnv/092a3a7afc1aa9f6f96322387552e87c/raw/6b90f11442fbce06ad564d42879f8ea2c3993e30/buma-calendar.min.js

**Comment by CodeBroJohn** [comment]
Was this every resolved? Because of this when I try to update state with datepicker.data.value() my application freezes because of how many times the even is fired.
