### ISSUE TITLE
How to show startDate and endDate in Input field?

### ISSUE THREAD

**Issue by hiNigel** [Wikiki/bulma-calendar#123]
I want to initialise the calendar with a date passed passed via django context.

I tried passing to the value attribute according to the format how it is filled when date ranges are selected from the calendar.

` <input type="date" id="datepicker" class="input" placeholder="Choose Dates"
                data-is-range="true" value="12-12-2018 - 13-12-2018">`

But I get this warning and the passed value is not displayed in the input field.

> The specified value "12-12-2018 - 13-12-2018" does not conform to the required format, "yyyy-MM-dd".

Any ideas?

**Comment by ony3000** [comment]
Can you see #110? I think this issue can be solved in the same way.
