### ISSUE TITLE
Can't resolve module 

### ISSUE THREAD

**Issue by konsvasi** [Wikiki/bulma-calendar#124]
I'm trying to integrate the bulma-calendar into my app, I followed the steps in the documentation but I'm getting the error `/src/Components/Datepicker.js
Module not found: Can't resolve '~bulma-calendar/dist/css/bulma-calendar.min.css' in '/home/user/Projects/act_track/src/Components'`

I can't figure it  out. This is how I do the imports on the top of the file
`import 'bulma/css/bulma.css';`
`import '~bulma-calendar/dist/css/bulma-calendar.min.css';`
`import bulmaCalendar from '~bulma-calendar/dist/js/bulma-calendar.min.js';`

it doesn't have a problem with finding the first file since I'm using it all over my project without any problems. Did I mess up with my imports?

**Comment by ony3000** [comment]
Did you try to remove the tilde?
In order to load a module from within a script, you need to write:

```diff
 import 'bulma/css/bulma.css';
-import '~bulma-calendar/dist/css/bulma-calendar.min.css';
-import bulmaCalendar from '~bulma-calendar/dist/js/bulma-calendar.min.js';
+import 'bulma-calendar/dist/css/bulma-calendar.min.css';
+import bulmaCalendar from 'bulma-calendar/dist/js/bulma-calendar.min.js';
```

If you using webpack and sass-loader together, you can use the following when loading stylesheet. (see [sass-loader](https://webpack.js.org/loaders/sass-loader/#imports))
```scss
@import "~bulma-calendar/dist/css/bulma-calendar.min.css";
```
