### ISSUE TITLE
Stray causing error when running npm

### ISSUE THREAD

**Issue by velu76** [Wikiki/bulma-calendar#129]
There is a stray semicolon at line 210 of file "node_modules/bulma-extensions/bulma-calendar/dist/css/bulma-calendar.sass"

Removing it, causes the error to disappear.
--------

This issue has had been raised as below in laravel-frontend-presets:
https://github.com/laravel-frontend-presets/bulma/issues/22#issue-391480094

**Comment by Wikiki** [comment]
duplicate with #126
