### ISSUE TITLE
BulmaCalendar no longer attaches on date field type

### ISSUE THREAD

**Issue by buildscientist** [Wikiki/bulma-calendar#131]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ x] Are you running the latest version?
- [x ] Are you reporting to the correct repository?

## Bug Report

**Environment**
- Extension version(s): 5.0.5
- Bulma version: 0.7.2
- OS: macOS Mojave, Windows 10 Pro
- Browser: all
- How you are customizing the extension: [e.g. yes/no]
Used in a VueJS component.

**Current Behavior**
bulmacalendar no longer attaches on an input field of type "date". 

**Input Code**
- Initialization code:

```html
          <div class="field">
            <input required type="date">
          </div>
```
```js
 const calendar = bulmaCalendar.attach(this.$refs.calendarTrigger, {
      startDate: this.date,
      showHeader: true,
      showFooter: true,
      isRange: true,
      labelFrom: "Start Date",
      labelTo: "End Date",
      displayMode: "inline"
    })[0];
```

**Comment by Wikiki** [comment]
Hi @buildscientist ,

the reason is to permit the use of the extension only on a set of date input and not all by default (in order to welcome the time selector extension which coming soon). Feel free to pass the ```[type="date"]``` selector when instantiating the extension to get back to the orginal behavior.
