### ISSUE TITLE
"Date Range" not possible same date

### ISSUE THREAD

**Issue by jirisarri10** [Wikiki/bulma-calendar#132]
Hi dear:
First over all, i love this calendar. I would like to highlight a possible bug or maybe suggestion for improvement.
When we are in date range mode and we want to select a date that goes from that day to the same day, the application does not take the date until, it only shows the lower date of the range and the calendar stays open until the user clicks on any other day than the previous date. However, the user double-clicks the "today" button, then a range of dates appears from today until today.
Thanks in advance.
yours sincerely

Javier Irisarri

**Comment by jirisarri10** [comment]
I regret it if I am repetitive, Is there an estimated date for fix bug? Thank in advance,with all my respect!!

**Comment by Wikiki** [comment]
Hi @jirisarri10,

sorry there is no estimated date to fix this bug. I'm quiet busy those days but I'll try to work on it before the end of this month.
