### ISSUE TITLE
How to make calendar wider than the input it's attached to?

### ISSUE THREAD

**Issue by airblade** [Wikiki/bulma-calendar#135]
## Bug Report

**Environment**
- Extension version(s): v5.0.5
- Bulma version: v0.7.1
- OS: macOS 10.14.2
- Browser: Chrome
- How you are customizing the extension: N/A

**Current Behavior**
I have a text input field for a date.  The field is not wide because the date string is not long.  However when I show the calendar, its width is constrained to my narrow next field and it looks squashed.  I would like it to take, say, twice the width of the text field.

Here is a screenshot.  I have actually made my input field wider than it was originally, just so the calendar isn't totally squished.  I would like the calendar's width to be independent of its input field, so I can make my field narrower while I make the calendar wider.

<img width="285" alt="screenshot 2019-01-21 at 1 16 37 pm" src="https://user-images.githubusercontent.com/7265/51476933-d0f03a00-1d7e-11e9-9c84-f2299577e282.png">

**Input Code**
- Initialization code:

```js
const selector = 'input[id$=dated_on]';

const options = {
  clearButton: false,
  showHeader: false,
  showFooter: false,
  toggleOnInputClick: false
};

const calendar = bulmaCalendar.attach(selector, options);
```

Thanks!

**Comment by Wikiki** [comment]
Hi,

please try with the new release (integrating a new design) and tell me if you are still facing the issue.

**Comment by airblade** [comment]
I'm away right now but I'll try it when I'm back.  Thanks!
