### ISSUE TITLE
Date parsing has been removed

### ISSUE THREAD

**Issue by airblade** [Wikiki/bulma-calendar#140]
## Bug Report

My date format is "DD MMM YY", e.g. 30 Jan 19.

In babf2730d the code parsed incoming dates according to the date format (see [here](https://github.com/Wikiki/bulma-calendar/commit/babf2730d0ea19bae1f27c2886f39566892fbe6d#diff-99a85c3932c0670278158f38d818e0efR194)).

However 6fba331 moved all this functionality into a new datePicker class but lost the parsing (see [here](https://github.com/Wikiki/bulma-calendar/commit/6fba3312259362e389e48ffaeb21fbe168b37637#diff-1f6f8e40ebcb7a97254088d41c497072R646)).  Instead the code now just instantiates a new date object with the element's value.

This makes a difference on Firefox where `new Date("30 Jan 19")` is interpreted as 19th January 2030 instead of 30th January 2019 (as on Chrome and Safari).

I am setting my text input's value attribute to an ISO 8601 date.  On page load bulma-calendar renders its correctly in DD MMM YY format.  But as soon as I open the calendar, the calendar is wrongly set to 19th January 2030.

I note that date-fns supports [parsing](https://date-fns.org/v1.29.0/docs/parse) dates.

Is this change intentional?  How can I get it to work with DD MMM YY?

**Comment by 2food** [comment]
I have a very similar issue. I want to display dates as "DD.MM.YYYY" and it works fine on Firefox but on Chrome it swaps the date and month when i open the calendar.
