### ISSUE TITLE
Events not firing on Bulma calendar

### ISSUE THREAD

**Issue by jspruance** [Wikiki/bulma-calendar#141]
Hello, I have instantiated one Bulma calendar in my React component but I have been unable to get the selected dates. 

This code is pretty much identical to the sample code in the documentation only I am working with just 1 calendar instance rather than iterating through an array of instances.  I have tried other events such as 'ready' and 'startDate:selected' but the event handler never gets fired. 

I have looked through the events documentation but not really finding any instruction on how to do this other than what's in the 'Quick Start' demo code. Also, React 'onChange' doesn't get triggered when the Bul;ma calendar updates the input so I can't use that either. 

Here is my code - appreciate any help here:

```
const accessReviewCalendar = bulmaCalendar.attach('.access-review-calendar', this.calendarOptions);

 accessReviewCalendar.on('date:selected', date => {
     console.log(date);
});
```

**Comment by Wikiki** [comment]
Hi,

events name have changed and I forgot to update the documentation. I will soon.
To get it work you can use following events:
```select:start``` ```select:end``` ```select``` ```show``` ```hide```

**Comment by amirkhh** [comment]
> Hi,
> 
> events name have changed and I forgot to update the documentation. I will soon.
> To get it work you can use following events:
> `select:start` `select:end` `select` `show` `hide`

Please update the documentation, everything has error in new version and I got a lot of undefined.

**Comment by Wikiki** [comment]
Hi,

documentation has been updated.

What do you mean by "everything has error" ?

**Comment by amirkhh** [comment]
Hi, But everything is like old documentation! have you updated this [link](https://creativebulma.net/product/calendar/demo) or I can't find the correct documentation ? 

I got some undefined in "cancel" and "today" button's label.

Is it possible for you to add a new feature to allow us to highlight some days in calendar ?

thanks

**Comment by Wikiki** [comment]
Hi,

This link has been updated. Please do a right click on the page and choose to refresh the frame content (you should have some cache for this frame content)

**Comment by sasdecompte** [comment]
hello,
please, 'select:start' event doesn't work, is there a new event replace it?

**Comment by BlackToothGrin96** [comment]
Hi, I am experiencing the same problem.

My html is as follows:
`<input type="date"
                                       data-display-mode="inline"
                                       data-is-range="true"
                                       data-close-on-select="false"
                                       data-is-range="true"
                                       data-show-header="false"
                                       data-show-footer="false"
                                       data-color="link"
                                       data-max-date="[03/09/2020]"
                                       id="dateSelect">`

And the various javascript methods I have tried:
`var calendar = bulmaCalendar.attach("#dateSelect");
            console.log(calendar);

            calendar[0].on("select", date => {
                console.log(date)
             });

            for (var i = 0; i < calendar.length; i++) {
                calendar[i].on('select', date => {
                    console.log(date);
                });
             }

            calendar[0].on("select", date => {
                console.log("DATE SELECTED: " + date);
                console.log(date);
             });

            var element = document.querySelector("#dateSelect");

            if (element) {
                element.bulmaCalendar.on("select", function(datepicker) {
                    console.log(datepicker.data.value());
                });
             }

            if (element) {
                element.addEventListener("select", function(datepicker) {
                    console.log(datepicker.data.value());
                });
            }`

But none of these events are firing; my initial `console.log(calender)` is working, so I know the code is executing.
I am also getting no errors in the console, just no firing of events.

I am importing Bulma and Bulma-Calendar from local staticfiles.

I am going to try a few more 'direct' methods and will post if I manage to capture some events.

Devs: Please fix!
This package is awesome and I would like to continue using it; if only the events work :cry:

**Comment by Zikoi5** [comment]
Still not fixed?

**Comment by BlackToothGrin96** [comment]
I'm not sure, this was for a work project so I ended up using the calendar from Metro UI.

**Comment by thedoglett** [comment]
Nudge - anyone figure out how to get select:start to work? 

Banging my head against a brick wall here…
