### ISSUE TITLE
have problem with event

### ISSUE THREAD

**Issue by mamadza** [Wikiki/bulma-calendar#142]
Hi I have lot of problem with event 
in new version event has been changed but the document doesn't update
the event ready isn't work in previous version
I have two problem , what the name of event when calendar (ready, rendered) loaded in Inline mode?
how can I pass multi day in calendar and show it (not range , not disableDates [ ] ) I want to access them and just access to click them and event called
another problem is undifiend on button 
![photo_2019-02-17_11-55-03](https://user-images.githubusercontent.com/12842935/52910332-4f22fc00-32ab-11e9-929e-89f11b56c432.jpg)

thank you

**Comment by Wikiki** [comment]
Hi,

documentation just has been updated.

Currently, it's not possible to pass multiple dates to the calendar. I'll think about adding this functionality.

I'll have a look on the "undefined" button title.

**Comment by mamadza** [comment]
can you explain and write sample about how can we  use event ready in "inline mode" ? 
because I need to do something when calendar is loaded ?

**Comment by Wikiki** [comment]
The 'ready' event handling has been fixed.
Please see the [codepen](https://codepen.io/CreativeBulma/pen/wNRwoL )to see how to use it.
