### ISSUE TITLE
focus block calendar position

### ISSUE THREAD

**Issue by jirisarri10** [Wikiki/bulma-calendar#143]
Hi there!!!
I am very grateful for your work. After fixing same date in date range... There is a new issue, in my opinion: the calendar does not fit the text box that executes it. It always appears in the same position, that is, in the upper left. It does not inherit underlying position
![captura de pantalla_2019-02-18_10-02-29](https://user-images.githubusercontent.com/36475731/52943192-81dcfb00-3364-11e9-9ab8-82d3c53e32c5.png)
Thank you very much for your great work!!!
Sincerely!!!
Javier Irisarri

**Comment by Wikiki** [comment]
Hi,

It seems you forget ton include bulma css first.
Try adding it and tell me.

**Comment by jirisarri10** [comment]
Hi,
Thanks for your quick reply!!
Always I included bulma.css. Look at the links the prefix n_ -> new version bulma calendar. If use o-> old version  bulma calendar, works fine!!!
new version:=mié 17 oct 2018,
old version:= dom 17 feb 2019
The simple code for trying is this:

<html>
 <head>
<meta charset="UTF-8" />

  <title></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.css" rel="stylesheet">
    <link href="bulma-calendar/dist/css/n_bulma-calendar.min.css" rel="stylesheet"> 
    <script src="bulma-calendar/dist/js/n_bulma-calendar.min.js"></script>
    
</head>
<body>
<center><input  type='date' id="calendar"></center>
</body>

<script>
var calendars = bulmaCalendar.attach('[type="date"]', {isRange:true});
console.log("calendars number: " +calendars.length);
for(var i = 0; i < calendars.length; i++) {
    calendars[i].on('date:selected',
 date=> {
	console.log("start-date:" +date.start);
        console.log("end-date" +date.end);
	});
	}
</script>


</html>

**Comment by Wikiki** [comment]
I'll have a look at the positioning issue.
