### ISSUE TITLE
calendars.lenght property not return

### ISSUE THREAD

**Issue by jirisarri10** [Wikiki/bulma-calendar#144]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

- [x] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [x] Are you running the latest version?
- [x] Are you reporting to the correct repository?

## Bug Report

**Environment**
- Extension version(s): [e.g. v1.0.0, ...]
- Bulma version: [e.g. v7.1 / v7.2]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- How you are customizing the extension: [e.g. yes/no]

**Current Behavior**
A clear and concise description of the behavior.

**Input Code**
- Initialization code:

```js
var bulmaCalendar = BulmaCalendar.attach();
```

**Possible Solution**
[Only if you have suggestions on a fix for the bug]

**Additional context/Screenshots**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via [codepen](https://codepen.io) or similar.

**Comment by jirisarri10** [comment]
Hello there.
I just checked that in the last version of the calendar the lenght porpiedad of the "calendars" object does not work ...

for (var i = 0; i <calendars.length; i ++)

calendars.lenght return undefined

**Comment by Wikiki** [comment]
Hi,

the returned value is an array only if multiple elements have been found and instatiated.
If only one element is instantiated (provided selector correspond to only one element in the page) then returned value is not an array but directly calendar instance.

**Comment by jirisarri10** [comment]
Hi there,
Thank you for your quick reply
Previously, I sent you the code with which I was testing. If I change the css and js to old versions, calendars.lenght returns 1 in the new version, it returns undefined.
Sincerely,
Javier

**Comment by Wikiki** [comment]
Hi,

pease note in last release (v6) instatiation always returns an array
