### ISSUE TITLE
input size and console.log values

### ISSUE THREAD

**Issue by jirisarri10** [Wikiki/bulma-calendar#145]
Hello
First of all, I would like to thank you for your effort and dedication. I just tried the calendar with the new version and now the INPUT size is the whole screen. It does not take into account the size of the input. In addition the calendar keeps appearing in the upper part of the left.
On the other hand, I tested the date object and it does not show the selected values: 
calendars [i] .on ('date: selected',
 date => {
console.log ("start-date:" + date.start);
console.log ("end-date" + date.end);
});
}
For last, the header of the calendar changed!!!

thank you very much.
I am grateful
Sincerely,

Javier Irisarri
![captura de pantalla_2019-02-18_21-29-11](https://user-images.githubusercontent.com/36475731/52977311-b97b8f80-33c4-11e9-9449-cf21a1923b8a.png)

**Comment by Wikiki** [comment]
Hi,

Thanks for your feedback.
Regarding the event: in your example use date.data.startDate / fate.data.endDate or directly date.data.value()

Can you try puting the input into a div and positin it as wanted then tell me if you still having picker positioning issiue ?

Yes, calendar header changed to displau all information in one place (date and time) you can now choose to use a datepicker, timepicker or datetimepicker

**Comment by Wikiki** [comment]
And notice that event is named 'select' not 'date:select'

**Comment by Wikiki** [comment]
For information, I've checked and fullwidth is the default size of bulma input element.
As mentioned you have to wrap it into a div (.control) to be able to specify a size and a position.

**Comment by jirisarri10** [comment]
Hi there!!!!
First of all I would like to thank you for your help, effort, dedication and magnificent project.
I was testing the new calendar bulma inside a div, as you suggested. On the other hand I have also tried bulma old calendar (October 22, 2018). The result is that with the new bullet calendar the adjustment the size of the input occupies the entire line. In addition, the calendar itself, appears on the left, independent of the input.
I pass several images: No bulma calendar, with bulma new calendar and bulma old calendar.
Finally, thank you so much for the console.log worked perfectly !!!!
A hug!!
![without_calendar](https://user-images.githubusercontent.com/36475731/53006716-a81a9d80-342d-11e9-857a-5a0834e79c5d.png)
![bulma_new_before_click](https://user-images.githubusercontent.com/36475731/53006733-b23c9c00-342d-11e9-81d4-5e744f94967a.png)
![bulma_new_after_click](https://user-images.githubusercontent.com/36475731/53006742-ba94d700-342d-11e9-8636-3744a88996a3.png)

![old_bulma_before_click](https://user-images.githubusercontent.com/36475731/53006787-d1d3c480-342d-11e9-83a6-5ee4527f48b9.png)
![bulma_old_after_click](https://user-images.githubusercontent.com/36475731/53006807-ddbf8680-342d-11e9-9365-e3fad2d71c7a.png)

**Comment by Wikiki** [comment]
Hi,

as you can see here: https://codepen.io/CreativeBulma/pen/rPPoXB
the style (width) of the input is the default bulma behavior. If you want to change that, just add a wrapper div with a css rule on datepicker wrapper (using the selector: ```[id^="datetimePicker"]```) and set a maximal width.

for example
```
.limited-width [id^="datetimePicker"] {
    max-width: 320px;
    margin: auto;
}
```

The calendar picker is always displayed from the left of the input in default display mode. It's the intended behavior.

**Comment by jirisarri10** [comment]
SUPER!!!!! WIKIKI!!! GENIAL!!!! SEEING MAGISTRALLY!!!
I apreciate your help!!!
Thank you so much!!!!!

![new_version_before_click](https://user-images.githubusercontent.com/36475731/53014582-ce960400-3440-11e9-9b91-0200ddf42c17.png)
![new_version_after_click](https://user-images.githubusercontent.com/36475731/53014611-e4a3c480-3440-11e9-8a0d-ab276fc7bf6a.png)
