### ISSUE TITLE
Cancel button in TimePicker

### ISSUE THREAD

**Issue by Observablerxjs** [Wikiki/bulma-calendar#148]
- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] Are you running the latest version?
- [X] Are you reporting to the correct repository?

## Bug Report

**Environment**
- OS: [ Windows 10]
- Browser: [ Chrome 71.0 ]

**Current Behavior**
I found this behavior on the demo.
When you click on 'Cancel' in the TimePicker the new time is applied anyway.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via [codepen](https://codepen.io) or similar.

You enter 03:00 and after you click on the input a second time and change for example to 05:00 and then click on "Cancel". 05:00 will be applied however the expected behavior is that it will keep 03:00 (or empty input if nothing was there in the first place).

**Comment by michael-hack** [comment]
Please test the new 6.1.1, this should fix the problem.
