### ISSUE TITLE
Make `showHeader` option work again... again

### ISSUE THREAD

**Issue by fabbrikk** [Wikiki/bulma-calendar#150]
Hi,
It's currently impossible to disable the header.
`
if (!this.options.showHeader) {
    this._ui.header.container.classList.add('is-hidden');
}
`

It was already resolved here https://github.com/Wikiki/bulma-calendar/commit/f94a9926d42f15e41d9ebebeb1161a060acca54f
and overwrited the same day by another merge...

Please resolve. Thanks

**Comment by Wikiki** [comment]
My bad. Sorry.

**Comment by fabbrikk** [comment]
Thankyou, good job btw!
