### ISSUE TITLE
How to hide footer section ?

### ISSUE THREAD

**Issue by ChDUP** [Wikiki/bulma-calendar#151]
Hi

I'm trying to hide footer section, but its still present.
I 've used data-show-footer as false.

Here is my input :
`<input data-start-date="2018-12-03" data-date-format="YYYY-MM-DD" data-show-footer="false" id="date" type="date" name="date" data-close-on-select="false" data-today-button="false" data-display-mode="inline" data-lang="fr" value="{{ old('date') }}" required autofocus>`

Thanks for your help

**Comment by Wikiki** [comment]
fixed in version 6.0.3
