### ISSUE TITLE
How to pre-select a date ?

### ISSUE THREAD

**Issue by ChDUP** [Wikiki/bulma-calendar#152]
Hi

I'm trying to pre-select a date, by using data-start-date but it doesn't work.
How can I do this ?

Here is my input :
`<input data-start-date="2018-12-03" data-date-format="YYYY-MM-DD" data-show-footer="false" id="date" type="date" name="date" data-close-on-select="false" data-today-button="false" data-display-mode="inline" data-lang="fr" value="{{ old('date') }}" required autofocus>`

I'm on a Laravel project, with a docker environment.
php version 7.3
bulma-calendar installed as a nodejs module

Thanks for your help

**Comment by Wikiki** [comment]
Hi @ChDUP ,

You forgot you input details.
Can you please update your post to give me more details about how you instanciate the calendar ?

**Comment by ChDUP** [comment]
Hi @Wikiki 
Sorry, I forgot the quote :-)

**Comment by Wikiki** [comment]
You used the right options.
Please try the last release (v6.0.3) it should fix your issue.

**Comment by ChDUP** [comment]
Yes it's ok now.
thanks !
