### ISSUE TITLE
minDate and maxDate aren't working

### ISSUE THREAD

**Issue by repne** [Wikiki/bulma-calendar#153]
DatePicker reads the value of **this.min** and **this.max** from **options.min** and **options.max**:
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/datePicker/index.js#L459
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/datePicker/index.js#L460

However, the setters are changing the value of **this._min** and **this._max**, which are never used:
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/datePicker/index.js#L96
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/datePicker/index.js#L106

The datePicker default options are **minDate** and **maxDate**, not **min** and **max**:
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/datePicker/defaultOptions.js#L8
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/datePicker/defaultOptions.js#L9

The same is also true for the defaultOptions of the calendar:
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/defaultOptions.js#L26
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/defaultOptions.js#L27

The calendar creates the datePicker passing its own options, so the datePicker will receive **minDate** and **maxDate**, not **min** and **max**:
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/index.js#L560

The calendar **minDate** and **maxDate** properties are also setting/getting the wrong fields from the datePicker, **minDate** and **maxDate** rather than **min** and **max**:
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/index.js#L167
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/index.js#L172
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/index.js#L177
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/index.js#L182

The documentations clearly says to use **maxDate** and **minDate**, however they are being ignored by the inner datePicker object as it uses **min** and **max** instead.

**Comment by Wikiki** [comment]
Hi,

I'll have a look on the minDate / maxDate issue but meanwhile the documentation is right: options properties are minDate and maxDate
internally the component use this._min and this._max but for convenience getters and setters are defined to work with those value using this.min and this.max.

**Comment by Wikiki** [comment]
I will try to clarify the code:

1. Instantiate new bulmaCalendar with minDate and maxDate options
2. In _init method: create a new datePicker instance using minDate and maxDate options
3. (in datePicker): use of options minDate and maxDate (coherent names with the one used when instanciating the component)
4. (in datepicker): in _init method: initialize this.min and this.date (equivalent to this._min and this._max) with options values (**The error is here: properties are minDate and maxDate not min and max**)



minDate and maxDate getters and setters in bulmaCalendar are just shortcuts to set and get minDate and maxDate value of datePicker
so to update minDate and maxDate of datePicker just call 'bulmaCalendarInstance.minDate = X'

**Comment by repne** [comment]
That won't work unfortunately, since minDate/maxDate is ignored by the picker.

This is my current workaround:
```
const options = {
      startDate: today,
      min: minDate, // should be minDate
      max: maxDate, // should be maxDate
      showFooter: false,
      displayMode: "inline",
      dateFormat: "DD/MM/YYYY"
    }
```

**Comment by Wikiki** [comment]
Yes that's what I said: the error is in the _init method of datepicker where options used are min and max instead of minDate and maxDate.
I've made the correction in the source but can't rebuild the component and publish it yet (I'll do it late today)

**Comment by shauryachawla** [comment]
this is still an issue?

**Comment by shauryachawla** [comment]
noob question here - i can't get the minDate attribute to work in html. am i doing something wrong?

**Comment by triwats** [comment]
@shauryachawla - just seen this but the documentation states that you could do this via input fields in HTML as well as within, which might be what you're looking for:

```Options can be set using input data attributes. Just convert option name to dashes.
For example if you want to init a deta picker using inline display style with range capability and a validate button:

<input type="date" data-display-mode="inline" data-is-range="true" data-close-on-select="false">
```

I think it would look something like this: 
```
<input type="date" data-display-mode="inline"= data-min-date="10/10/1984">
```

It will have to be in accordance with the date format you specified.
