### ISSUE TITLE
SASS compilation error

### ISSUE THREAD

**Issue by repne** [Wikiki/bulma-calendar#154]
When importing the .sass file in the dist folder:
`@import "bulma-calendar/dist/css/bulma-calendar.sass";`
I'm getting the error:
`Error: semicolons aren't allowed in the indented syntax.`
This is caused by a semicolon at this line:
https://github.com/Wikiki/bulma-calendar/blob/master/dist/css/bulma-calendar.sass#L210

**Comment by Wikiki** [comment]
Hi,

the issue is only in the dist sass file.
Please use the sass fil from source folder until I recommit the dist folder.

**Comment by repne** [comment]
Please also fix mixed tabs/spaces in the timepicker.sass.
Spaces starts at this line:
https://github.com/Wikiki/bulma-calendar/blob/master/src/sass/timepicker.sass#L138
But before that it's only tabs.

**Comment by Wikiki** [comment]
Rhaaaa.....
I'll completely review my release.
