### ISSUE TITLE
When adding the calendar to a page, every button in that page stops working

### ISSUE THREAD

**Issue by repne** [Wikiki/bulma-calendar#155]
The calendar registers a listener for click and touch events of the whole page body:
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/index.js#L728

Then the listener sinks these events rendering all buttons in that page non functional:
https://github.com/Wikiki/bulma-calendar/blob/master/src/js/index.js#L273

The current workaround is to use an **inline** calendar and remove the listener:
```
    const calendars = bulmaCalendar.attach('input[type="date"]', options);
    calendars.forEach((calendar: any) => {
      ['click', 'touch'].forEach(clickEvent => {
        document.body.removeEventListener(clickEvent, calendar.onDocumentClickDateTimePicker);
      });
    });
```

**Comment by Wikiki** [comment]
Hi,

thanks for all your feedbacks.
I'll fix it.
