### ISSUE TITLE
Unable to get the selected date with VueJS

### ISSUE THREAD

**Issue by cashismatt** [Wikiki/bulma-calendar#156]
Can't get the date selected with vuejs. I attached the calendar on the mounted hooks but it doesn't give me back the date. Bulma-calendar version 6.0.3.

Notice that if I switch to 5.0.0 it works, but I don't want this version because is unstyled with display mode "dialog".

This is my actual code:

This is my code:
const calendars = bulmaCalendar.attach('[type="date"]', {
        displayMode: "dialog",
        closeOnSelect: "false",
        isRange: "false",
        lang: "en",
      });
      for(var i = 0; i < calendars.length; i++) {
        console.log(calendars[i])
        calendars[i].on('date:selected',date => {
          console.log(date)
        });
      }

**Comment by Wikiki** [comment]
Hi,

In v6 events name has changed (please see documentation for details). In your case you should use ```select``` event

**Comment by cashismatt** [comment]
I took the event from the documention.
But anyway I just changed selected with select but it still dosn't work

**Comment by Wikiki** [comment]
Strange because the documentation here (https://creativebulma.net/product/calendar/demo) give the right events name (in your case ```select``` and not ```date:selected``` nor ```date:select```

**Comment by lauhakari** [comment]
Actually, both ES6 and VueJS examples display `calendar.on('date:selected'` ...

**Comment by Wikiki** [comment]
You're rights ES6 and VueJS example are wrong. My bad. I'll fix them

**Comment by sts-ryan-holton** [comment]
I'm having the same issue, seems to still be broken

```js
/**
 * Init custom datetime picker from Bulma
 */
initDateTimePicker: function () {
  const calendar = bulmaCalendar.attach(this.$refs.calendarTrigger, {
    type: 'datetime',
    dateFormat: 'YYYY-MM-DD HH:00:00',
    displayMode: 'dialog'
  })[0]
  calendar.on('date:selected',date => {
    console.log(date)
  });
}
```

**Comment by Wikiki** [comment]
Hi @sts-ryan-holton ,

have you seen this reply :

> Strange because the documentation here (https://creativebulma.net/product/calendar/demo) give the right events name (in your case `select` and not `date:selected` nor `date:select`)

example in documentation have not been updated yet.
