### ISSUE TITLE
Android 5: Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by lordcoste** [Wikiki/bulma-calendar#158]
## Bug Report

**Environment**
- Extension version(s):v6.0.3 and master
- OS: Android 5.1.1 
- Browser: WebView in com.android.browser (39.0.0.0) (it works on Android Chrome 57)

**Current Behavior**

```
Uncaught TypeError: undefined is not a function bulma-calendar.js:18882:20 
_bindEventsbulma-calendar.min.js:18809 
_initbulma-calendar.min.js:18398 
datePickerbulma-calendar.min.js:13934 _
initbulma-calendar.min.js:13579 
```

```
var months = this._ui.body.months.querySelectorAll('.calendar-month') || [];

months.forEach(function (month) { // this is line 18882
    _this3._clickEvents.forEach(function (clickEvent) {
        month.addEventListener(clickEvent, _this3.onMonthClickDatePicker);
    });
});
```

We are working on an old android box with Android 5.1.1 and WebView in com.android.browser (39.0.0.0). We can't get this plugin work because "Uncaught TypeError: undefined is not a function". The same code works fine on the same OS using Chrome 57 app, but unfortunately we need to make it works on the obsolete webview.

It can be reproduced also on the emulator: Android studio, device with android 5.1 API 22.

Is there any workaround? I'm willing to customize the plugin's code to make it works.

Regards

**Comment by Wikiki** [comment]
Hi,

Can you try to console.log months value at this line ? I'm wondering if it's not because the webview does not handle the line <code>var months = this._ui.body.months.querySelectorAll('.calendar-month');</code>.

**Comment by lordcoste** [comment]
Thank you for the quick reply, here is the result:

```
NodeList[0]
length: 0
```

**Comment by lordcoste** [comment]
if it can help here is the output of

`console.log(this._ui.body.months);`

`<div class="datepicker-months"></div>`

**Comment by Wikiki** [comment]
Hi,

Can you share a sample project code for Android Studio with me to be able to test and try to debug it ?

Regards

**Comment by lordcoste** [comment]
Sure, I've made a minimal webview project with bulma-calendar. Here it is:

https://github.com/lordcoste/bulma-calendar-webview

**Comment by Wikiki** [comment]
Okay, the issue is related to the function forEach which does not seems to be available on this version of webView. Please try to compile the extension after changing <code>"browsers": [ ">0.25%", "ie 11"]</code> to a value which integrates your browser (see at https://github.com/browserslist/browserslist for available values).
If you don't want to recompile the extension you can also replace all <code>myArray.forEach()</code> calls by a older style <code>for (var i=0; i<myArray.length; i++) {</code>

example, switch from
```javascript
months.forEach(function (month) {
    _this3._clickEvents.forEach(function (clickEvent) {
        month.addEventListener(clickEvent, _this3.onMonthClickDatePicker);
    });
});
```

To


```javascript
for (var i=0; i<months.length; i++) {
    _this3._clickEvents.forEach(function (clickEvent) {
        months[i].addEventListener(clickEvent, _this3.onMonthClickDatePicker);
    });
}
```

**Comment by lordcoste** [comment]
Thank you, after your suggestion I've been able to solve using polyfill on NodeList forEach:

```
if (window.NodeList && !NodeList.prototype.forEach) {
    NodeList.prototype.forEach = Array.prototype.forEach;
}
```

**Comment by Wikiki** [comment]
Right I didn't thought about polyfill :-p

Good to know it's working.
