### ISSUE TITLE
Update website with latest version and docs

### ISSUE THREAD

**Issue by buildscientist** [Wikiki/bulma-calendar#160]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ ] Are you running the latest version?
- [x] Are you reporting to the correct repository?

## Bug Report

The website at [wikiki.github.io](https://wikiki.github.io/components/calendar/) references v5.0.0 of the calendar and older documentation. Please update so that we're not having to dig through issues to find the correct documentation. Thanks.

**Environment**
NA

**Current Behavior**
A clear and concise description of the behavior.

**Input Code**
- Initialization code:
NA

**Possible Solution**
[Only if you have suggestions on a fix for the bug]

**Additional context/Screenshots**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via [codepen](https://codepen.io) or similar.

**Comment by Wikiki** [comment]
fixed
