### ISSUE TITLE
No event on clear

### ISSUE THREAD

**Issue by Adiqq** [Wikiki/bulma-calendar#164]
**Is your feature request related to a problem? Please describe.**
I'm using React, datetime picker is used for dynamic filtering of data. I need event to know that value has been cleared.

**Describe the solution you'd like**
Either call to "selected" event or some new event.

**Comment by TheMaikXX** [comment]
Hello, can you please update docs about this event (it's missing there)
Docs I use: `https://bulma-calendar.onrender.com/`

Thanks,
have a nice day
