### ISSUE TITLE
'type' option can't be set 

### ISSUE THREAD

**Issue by gedeef** [Wikiki/bulma-calendar#165]
## Bug Report

**Environment**
- Bulma version: bulma-calendar@6.0.4
- OS:  Windows 10
- Browser: Chrome 73.0.3683.86 
- How you are customizing the extension: no
- Using in Vue.js and Laravel

**Current Behavior**
I'm trying to initialize a calendar without time, but the options.type property is always 'datetime', no matter what I specify.

**Input Code**
- Initialization code:
```html
<<!-- in my component.vue -->
<button ref='calendarTrigger' type='button'>Change</button>
```

```js
//in bootstrap.js
window.bulmaCalendar = require('bulma-calendar');

//in component.vue
var d = new Date();
d.setDate(d.getDate() - 7);
let options = {
  startDate: d,
  type: 'date',     //this line has no effect !
  color: 'info',
  isRange: true,
  dateFormat : 'DD/MM/YYYY',
  cancelLabel : 'Annuler',
  clearLabel : 'Réinitialiser',
  todayLabel : 'Aujourd\'hui',
  validateLabel : 'Ok',
  endDate : new Date(),
  weekStart : 1,
  timeFormat : '',
};
options['type'] = 'date'; //tried that cause I suspected a property named type could be a problem, didn't change anything
window.calendar = bulmaCalendar.attach(this.$refs.calendarTrigger, options)[0];
```

```js
//in chrome console
> calendar.options.type; 
< "datetime"
```

**Comment by wildthought** [comment]
I am having same issue, tried to use it in my asp.net app but type option doesn't work.

**Comment by Wikiki** [comment]
Hi,

do you have the issue when setting the attribute <code>type="date"</code> to the input element ?

**Comment by Tchilly** [comment]
Getting the same issue, unable to set type.  type=text, type=date doesn't matter.

**Comment by Wikiki** [comment]
Hi, I'll take a look on this issue next week (sorry I'm not available until next week to work on it)
