### ISSUE TITLE
Date Range bug selecting dates again crossing previous dates

### ISSUE THREAD

**Issue by rafarx** [Wikiki/bulma-calendar#166]
I'm getting "Error: The start of the range cannot be after the end of the range" when I select a date range and then try to select again a new range which any of the dates are after the previous selected end date.

Example:

Select a date range from 04/04/2019 to 04/06/2019 (2 days)
Select a date range from 04/05/2019 to 04/07/2019 (2 days) <- Crash (Errors in console)

Seems validation of dates is being made on the previously selected date.

**Comment by Wikiki** [comment]
PR #167 merged.
Thanks.
