### ISSUE TITLE
NPM non updated

### ISSUE THREAD

**Issue by AleeeKoi** [Wikiki/bulma-calendar#169]
## Bug Report

**Dev**
- Extension version(s): 6.0.4
- Bulma version: 7.2
- OS: Windows 10
- Browser: all
- How you are customizing the extension: no

**Current Behavior**
NPM package seems to be not updated, there is a bug with reselecting with date range who was already been fixed by following commit:

https://github.com/Wikiki/bulma-calendar/commit/67ed0a9f153b5893355c521ec08aa4847719a396

Pls update NPM

Thanks

**Comment by Wikiki** [comment]
v6.0.5 has just been published on NPM.
