### ISSUE TITLE
Support for the Spanish language?

### ISSUE THREAD

**Issue by lgalindo-dev** [Wikiki/bulma-calendar#17]
Could you add support for the Spanish language?

`
es: {
  weekStart: 1,
  previousMonth: 'Mes anterior',
  nextMonth: 'Próximo mes',
  months: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
  monthsShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
  weekdays: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
  weekdaysShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab']
}
`

**Comment by Wikiki** [comment]
Hi @lgalindo-dev,

could you please create a PR for it ?

**Comment by lgalindo-dev** [comment]
Done!, Thanks!
