### ISSUE TITLE
Sass compile parrent selector error

### ISSUE THREAD

**Issue by AleeeKoi** [Wikiki/bulma-calendar#170]
# Bug Report

**Environment**
- Extension version(s): 6.0.4
- Sass 1.15.2
- Sass loader 7.1.0

Hello, importing sass file:

`@import '~bulma-calendar/src/sass/index';`

I got following error:

```
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

        &.is-#{$name}
^
      Top-level selectors may not contain the parent selector "&".
    ╷
122 │     &.is-#{$name}
    │     ^^^^^^^^^^^^^
```

Same error whit line 131.
I think timepicker.sass is not indent correctly.

Can you fix it? Tnx.

**Comment by JoshuaBedford** [comment]
I'm having the same issue here.
