### ISSUE TITLE
minDate not working

### ISSUE THREAD

**Issue by JoshuaBedford** [Wikiki/bulma-calendar#175]
I'm unable to get minDate working. It doesn't throw any errors, but it doesn't restrict the user to only choosing after the mindate. I did a `console.log()` and the date i'm passing in is correct.

```
        var options = {
            'type': 'datetime',
            'dateFormat': 'YYYY-MM-DD',
            'minDate': new Date(Date.now() + 12096e5)
        };

        // Initialize all input of type date
        var calendars = bulmaCalendar.attach('[type="date"]', options);
```
I pulled this in through npm into a Laravel project.

**Comment by michael-hack** [comment]
Fixed with 6.1.5
