### ISSUE TITLE
DateTime requires a second click on the text field to register the time

### ISSUE THREAD

**Issue by musthavesteve** [Wikiki/bulma-calendar#177]
When I set the date, then proceed to specify a time - then click off the calendar, the date registers correctly in the text field but the time always appears as 00:00 until I click on the text field again (thus bringing the calendar up again).  I know the actual value is being changed (so if people click submit before hitting the text box again, the correct value is being sent) - but it just doesn't show up correctly on the text field!  Any thoughts?

Just to clarify:
1) Click on text field.
2) Calendar comes up.
3) Set date.
4) set time.
5) click off calendar
6) Date registers correctly in the text field, but time is 00:00 (though I know the actual value is set correctly because when I submit the form the data is correct).
7) If you click the text field again, it changes the text field to the correct time.

**Comment by yackSpillsaps** [comment]
Additionally, the time in the text field does not update as you update the time on the picker, while the date in the text field does update when you select a date on the calendar.

**Comment by michael-hack** [comment]
Fixed
