### ISSUE TITLE
Cancel Button Behavior

### ISSUE THREAD

**Issue by schematis** [Wikiki/bulma-calendar#178]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

- [x] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [x] Are you running the latest version?
- [x] Are you reporting to the correct repository?

## Bug Report

**Environment**
- Extension version(s): 6.0.7
- Bulma version: 0.7.5
- OS: Windows 10
- Browser: all
- How you are customizing the extension: CSS styling to bring input styling in line with bulma inputs

**Current Behavior**
Several issues related to the cancel button:
1. Unable to disable with `showClearButton: false` or `data-show-clear-button="false"`
2. If the date input is in a form, clicking the button submits the form and doesn't reset the field.

**Input Code**
- Initialization code:

```js
componentDidMount() {
    bulmaCalendar.attach('input[type="date"]', {
      type: "date",
      showClearButton: false,
      isRange: true,
      startDate: moment().subtract(1, "month"),
      endDate: moment(),
      maxDate: moment(),
    });
  }
```

**Possible Solutions**
I only have solutions for the part of the last one:
2. Buttons without a type default to a submit behavior. Add `type="button"` to fix the form submittal part.

**Comment by michael-hack** [comment]
Fixed
