### ISSUE TITLE
startDate should be colored somehow

### ISSUE THREAD

**Issue by jcerdan** [Wikiki/bulma-calendar#18]
Hi,

I'm using this Bulma extension and have seen that startDate is not marked somehow. instead the current date is rounded by a green circle. I think that the startDate should be rounded by a red circle or similar so you know which date is currently selected.
This is specially useful when using the calendar in overlay mode as as the field with the current ate is hidden.
Is there an option to fix that?

regards,

**Comment by Wikiki** [comment]
Hi,

there is no way to manage that witht he current version.
I'll work on it.

**Comment by jcerdan** [comment]
ok thanks, great!

**Comment by Wikiki** [comment]
Hi @jcerdan,

it's been fixed.
Now the date from input is take into account.

regards
