### ISSUE TITLE
help needed, set the startDate and endDate

### ISSUE THREAD

**Issue by JumBay** [Wikiki/bulma-calendar#182]
Hi,

This is not a bug, but rather some help needed.

I'd like to change the `startDate` and `endDate` from a Range datePicker.

From the doc, I've read there are getter/setter for `startDate` and `endDate` but what's format to use? I've tried with a `Date` or `string` but none work.

I've only managed to set the `startDate` by calling: `inst.value(new Date())` but it clears the `endDate`

Anyway thanks for this great extension.

**Comment by HoKangInfo** [comment]
----
yourformat='YYYY-MM-DD'
inst.value(yourformat(new Date()), yourformat(new Date()))
inst.save()
----
can work
