### ISSUE TITLE
Datepicker select function ignores dateFormat

### ISSUE THREAD

**Issue by glappsi** [Wikiki/bulma-calendar#184]
Version 6.0.7

Above issue leads to wrongly formatting some date formats after clicking into the input field, for example when using the format `'DD.MM.YYYY'`. It converts the string '06.11.2019' to the eleventh of june 2019 when using `new Date( '06.11.2019' )`. Please "unformat" the input before calling `new Date`.

**Comment by drecchia** [comment]
duplicated #193
