### ISSUE TITLE
new learner don't know how to use method ( show(), hide(), isOpen(), ... )

### ISSUE THREAD

**Issue by MakRatanakKh** [Wikiki/bulma-calendar#189]
Hi.
I'm new here.
And I would like to know how to use it method like: `show()`, `hide()`, ... etc.
So where can I put it to implement?
I have no idea.
I just follow the documentation:
![image](https://user-images.githubusercontent.com/46364520/61100281-d9087700-a48f-11e9-8b20-6f5e077c93e0.png)
But don't now where to put the code.
Please, help. thanks 😃

**Comment by CreativeBulma** [comment]
Hi,

chapter ```3. Initiate component```of the documentation shows how to access to instances and call method from the calendar instance.

Exemple:
```javascript
// To access to bulmaCalendar instance of an element
var element = document.querySelector('#my-element');
if (element) {
	// bulmaCalendar instance is available as element.bulmaCalendar
	element.bulmaCalendar.show();
}
```

regards
