### ISSUE TITLE
DD/MM/YYYY Issue on click

### ISSUE THREAD

**Issue by JacksonJeans** [Wikiki/bulma-calendar#193]
The error occurs as follows if you want to use the DD/MM/YYYY format.

If DD is less than 13, the format is converted to MM/DD/YYYY after the click event, so you can't navigate in the wrapper anymore, because there is a wrong date in the selection (example: 01/07/2019 in June becomes 07/01/2019 in January, and you navigate in the January selection).

Here is a temporary fix for those who have the same problem with the DD/MM/YYYY format.

The fix resets the event and returns false at the end so that bulma calendar does not open the wrapper and triggers the error. We now open it ourselves by toggling the "is-active" CSS class.

Now the wrapper opens and executes the selected date on click events and returns it in the set DD/MM/YYYY format.

Code:
`  $('input.datetimepicker-dummy-input').click(function(event){
    console.log('Datetime Picker wurde aufgerufen');   
    event.preventDefault();  
    var datetimepicker =  $(this).parent().parent().parent().children('.datetimepicker-wrapper').children('.datetimepicker');
    $(datetimepicker).toggleClass('is-active');
    return false;
  });`

**Comment by RevolteSolutions** [comment]
thanks for this quick solution, 
The error occurs also in other date formats like DD.MM.YYYY.

**Comment by rafarx** [comment]
> 
> 
> The error occurs as follows if you want to use the DD/MM/YYYY format.
> 
> If DD is less than 13, the format is converted to MM/DD/YYYY after the click event, so you can't navigate in the wrapper anymore, because there is a wrong date in the selection (example: 01/07/2019 in June becomes 07/01/2019 in January, and you navigate in the January selection).
> 
> Here is a temporary fix for those who have the same problem with the DD/MM/YYYY format.
> 
> The fix resets the event and returns false at the end so that bulma calendar does not open the wrapper and triggers the error. We now open it ourselves by toggling the "is-active" CSS class.
> 
> Now the wrapper opens and executes the selected date on click events and returns it in the set DD/MM/YYYY format.
> 
> Code:
> ` $('input.datetimepicker-dummy-input').click(function(event){ console.log('Datetime Picker wurde aufgerufen'); event.preventDefault(); var datetimepicker = $(this).parent().parent().parent().children('.datetimepicker-wrapper').children('.datetimepicker'); $(datetimepicker).toggleClass('is-active'); return false; });`

This doesn't work on mobile where the calendar is suppose to overlay the screen. Also if you click on the parent element "datetimepicker-dummy-wrapper" it triggers the error as well.

**Comment by drecchia** [comment]
Same problem here, thanks for the workaround.
