### ISSUE TITLE
startDate displays wrong date

### ISSUE THREAD

**Issue by sgandolfo** [Wikiki/bulma-calendar#194]
Hi,

I’m trying to set the startDate and I noticed that the startDate that is being displayed is the actual time + 12 hours.

I first declare a const to store the actual data and time
`const today = new Date();`

Then I’m assigning that value to the startDate option in the options object to be passed to the calendar constructor:

`const options = {
	lang: "nl",
	showHeader: false,
	weekStart: 1,
	minuteSteps: 1,
	disabledWeekDays: [0],
	validateLabel: "OK",
	startDate: today,
	minDate: today
};`

If I console.log the today variable I get the following output: “Thu Jul 18 2019 17:08:57 GMT+0200 (Central European Summer Time)”. The calendar shows this:

![image](https://user-images.githubusercontent.com/49209915/61469093-ea192280-a97e-11e9-8772-e2735a8dc86d.png)

So instead of showing the value of the today constant, it’s showing the today value + 12 hours. Do you have any idea what I’m doing wrong or is this a bug?

Many thanks for your support!

Kind regards,
Stefano

**Comment by michael-hack** [comment]
Should be fixed with 6.1.5
