### ISSUE TITLE
How to reset minDate at runtime

### ISSUE THREAD

**Issue by amuagarwal** [Wikiki/bulma-calendar#196]
I am using latest version of extension. My code is as follow:
const startDate = some random date;
bulmaCalendar.attach('[id="in-out-date"]', {
            color: "link",
            dateFormat: "DD-MMM-YYYY",
            showHeader: false,
            weekStart: 1,
            displayMode: "inline",
            showFooter: false,
            minDate: new Date(startDate.year(), startDate.month(), startDate.date()),
            maxDate: new Date(),
            startDate: new Date(),
            onReady:test(startDate)
        });

The in-out-date control is the single control which have different minDate value on the basis of table row selection. I tried onReady call back also, but it not refreshing the disabled date as per the new min date.
test(startDate) {
        const dateControl = document.querySelector("#in-out-date");
        if (dateControl.bulmaCalendar) {
            dateControl.bulmaCalendar.datePicker.options.minDate = new Date(startDate.year(), startDate.month(), startDate.date());
            dateControl.bulmaCalendar.refresh(true);
        }
    }

Please help how i can refresh the ui after change in minDate or MaxDate.
Also like to know how can i change the min and max year range in year selector

Thanks in Advance

**Comment by hsson** [comment]
I would love to know this as well. Also, how do you refresh the invalidDates array?

**Comment by k1oo** [comment]
You can reset minDate at runtime using code below.

`const [calendar] = bulmaCalenar.attach(<selector>, <...options>)    ##define calendar`
`calendar.datePicker.min = start;    ##setting minDate option of datepicker`
`calendar.datePicker.refresh();    ##refresh datepicker`
