### ISSUE TITLE
Bind Input with VueJS

### ISSUE THREAD

**Issue by nickcn** [Wikiki/bulma-calendar#197]
- [ Y ] Are you running the latest version?
- [ Y ] Are you reporting to the correct repository?

## Bug Report

**Environment**
- Extension version(s): [6.0.7]
- Bulma version: [0.7.5]
- OS: [Linux]
- Browser: [all]
- How you are customizing the extension: [no]

**Current Behavior**

This is more of a question than an issue. Is it possible to use this extension with the **v-model** directive in VueJS? I have been trying to do that, but no luck, unfortunately.
Maybe it has to do with the fact that bulma-calendar is attached on my element so the element "loses" the v-model directive? I can't seem to figure out if this is an issue on my code or expected behaviour, so sorry if this is not the place to ask.

**Sample code**
```
<template>
  <div class="block">
    <div class="block">
      <button ref="calendarTrigger" v-model="date" type="button">Change</button>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      date: new Date()
    };
  },
  mounted() {
    const calendar = bulmaCalendar.attach(this.$refs.calendarTrigger, {
      type: "datetime",
      color: "dark",
      weekstart: 1,
      minuteSteps: 1,
      dateFormat: "DD-MM-YYYY",
      timeFormat: "HH:mm"
    })[0];
    calendar.on("date:selected", e => (this.date = e.start || null));
  }
};
</script>
```

Thanks in advance.

**Comment by benjheath0** [comment]
did you ever figure this out?

**Comment by nickcn** [comment]
No, I ended up using another component.

**Comment by fabiopaitra** [comment]
I was thinking of using this plugin with my vue app, but looks like it got some limitations :/

**Comment by nickcn** [comment]
@fabiopaitra, I used this: https://www.npmjs.com/package/vue-flatpickr-component.
If you like bulma-calendar better, you could try and create a component using this and emit an event which would simulate the v-model behavior. See this for example: https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components.

**Comment by michael-hack** [comment]
Take a look at the new provided VueJS Component in 6.1.5
