### ISSUE TITLE
Latest releases no longer have a sass file in dist\css

### ISSUE THREAD

**Issue by JohnAherne** [Wikiki/bulma-calendar#202]
Is there a reason why there is no longer a sass file supplied in the dist\css folder.

Thanks for any info

**Comment by quen2404** [comment]
Same question ! any news @Wikiki ?

**Comment by Wikiki** [comment]
Hi,

that's right: sass file are available in src/sass directory and will not be available in dist folder anymore. Use the one from src/sass directory now.
