### ISSUE TITLE
How To set Start date and End date dinamically

### ISSUE THREAD

**Issue by leunam90** [Wikiki/bulma-calendar#207]
Hi, Im new using bulma calendar, im trying to set an enddate and startdate from a ajax request, ive already initiate the calendar, how can i reset it and set the new startdate and enddate... 

thank you so much for your help

**Comment by drecchia** [comment]
el.bulmaCalendar.datePicker.value(new Date(value));
    el.bulmaCalendar.datePicker.refresh();

    el.bulmaCalendar.timePicker.value(new Date(value));
    el.bulmaCalendar.timePicker.refresh();
    
    el.bulmaCalendar.save();

**Comment by datermine** [comment]
Is it possible the setters don't exist? I can't seem to figure this out either.

**Comment by Zernix** [comment]
as for startdate display i set it using jquery like this:

`$(".datetimepicker-dummy-input").val(mydynamicval);`

the startdate itself is onetime only when creating the calendar, so i ended up using this method.

**Comment by zringele** [comment]
```
                this.bulmaCalendar.datePicker.clear();
                this.bulmaCalendar.datePicker._select(end.toISOString());
                this.bulmaCalendar.datePicker._select(start.toISOString());
```
This is the workaround i found

**Comment by michael-hack** [comment]
Use the value() method.
