### ISSUE TITLE
Date format when initializing

### ISSUE THREAD

**Issue by isaya07** [Wikiki/bulma-calendar#21]
I use the DatePicker class on an input.
My date format is dd/mm/yy (also in the input) but in the _init function of the class you inititialize the date without reformating so the Date is set in this format: mm/dd/yy.
It's would be cool if it use the same format as the output of the class
Thanks

**Comment by Wikiki** [comment]
Thanks fot notifying this.
I'll fix it.

**Comment by Wikiki** [comment]
Fixed by commit 534d254
