### ISSUE TITLE
Year right arrow skips two years, not one

### ISSUE THREAD

**Issue by sorliem** [Wikiki/bulma-calendar#22]
I'm using bulma-calendar in my project and I noticed that the "year forward" arrow skips two years ahead, not one. The "year backward" arrow skips back one year.

Is skipping ahead two years the expected behavior?

![skip_2_years](https://user-images.githubusercontent.com/5680010/35835075-dc61e62e-0a95-11e8-8161-37ce2a6c838e.gif)

**Comment by Wikiki** [comment]
Hi @sorliem,

can you please update to the last version and see if you'r still facing the issue ?

regards

**Comment by sorliem** [comment]
I was at v0.1.9 and I've now updated to v0.2.1, still getting the same result.

```
$ cat package.json
{
  "repository": {},
  "license": "MIT",
  "scripts": {
    "deploy": "brunch build --production",
    "watch": "brunch watch --stdin"
  },
  "dependencies": {
    "bulma": "^0.6.2",
    "bulma-calendar": "^0.2.1",
    "jquery": "^3.2.1",
    "phoenix": "file:../../deps/phoenix",
    "phoenix_html": "file:../../deps/phoenix_html"
  },
  "devDependencies": {
    "babel-brunch": "6.0.6",
    "brunch": "2.10.7",
    "clean-css-brunch": "2.10.0",
    "sass-brunch": "^2.10.4",
    "uglify-js-brunch": "2.1.1",
    "whatwg-fetch": "^2.0.3",
    "uuid": "^3.2.1"
  }
}
```

**Comment by Wikiki** [comment]
Which browser are you using ?
Because on the documentation page with Firefox I have not this problem.

**Comment by Wikiki** [comment]
I've also tested with Chrome, Opera and Safari and its working fine.

**Comment by sorliem** [comment]
Hm, my calendar box looks different than the one in the documentation. 
<img width="319" alt="screen shot 2018-02-07 at 8 40 53 am" src="https://user-images.githubusercontent.com/5680010/35925349-b7e8e8ee-0be2-11e8-82be-14a776d5effb.png">

**Comment by Wikiki** [comment]
Check the calendar box HTML structure. It changed a bit

**Comment by Wikiki** [comment]
Hi @sorliem,

any news ? I'd like to help you if you're able to reproduce the error in a codepen.

**Comment by sorliem** [comment]
Hi @Wikiki. It's fixed now in our project. I think we just had to update it. Thanks for the help!
