### ISSUE TITLE
'crypto' is not defined on IE 11 when attaching calendar

### ISSUE THREAD

**Issue by rollscia** [Wikiki/bulma-calendar#220]
Hello,
I just finished a site including your nice calendar, but suddenly discovered that it doesn't work on **IE 11.** Yes we all hate IE 11, but unfortunately there is still lot of people to use it.
I get the error 

> crypto is not defined 

when trying to attach calendar :(
Nothing is displayed. I am really stuck. Any fix? 🙏

This is my code, nothing special:
```
var options = {type: 'date', displayMode: 'inline', isRange: true, allowSameDayRange: false, minDate: today, maxDate: endDate, closeOnSelect: false, disabledDates: busyDates, labelFrom: "da", labelTo: "a", lang: 'it', showTodayButton: false};

var calendar = bulmaCalendar.attach('[id="apt-calendar"]', options);
```

**Comment by khanhdv192** [comment]
Add this code as global variabble
```
var crypto = window.crypto || window.msCrypto;
```
