### ISSUE TITLE
strange(st) thing :-)

### ISSUE THREAD

**Issue by adas172002** [Wikiki/bulma-calendar#222]
## Bug Report

**Environment**
- Extension version(s): 6.0.7
- Bulma version: 0.8.0
- OS: macOS 10.14.6
- Browser: Safari 13.0.4

**Current Behavior**
Calendar rendering looks like a April's Fool Day joke, days are mixed (please see a screen shot)

**Input Code**
- Initialization code:
I am trying to use bulmaCalendar in Rails 6.0.2.1, in a new app that I just started developing this year. I use `data-` attributes for options passed to input field initialised as calendar
```js
document.addEventListener("turbolinks:load", () => {
  bulmaCalendar.attach("form #date[type='text']");
})
```
```ruby
<%= text_field_tag :date, nil, class: 'input is-black', placeholder: '13.12.2019', 
data: {
  label_from: 'Start date', 
  label_to: 'End date', 
  is_range: true, 
  date_format: 'DD.MM.YYYY', 
  week_start: 1, 
  color: 'grey'
} %>
```

**Additional context/Screenshots**
![Screenshot 2020-01-03 at 20 38 31](https://user-images.githubusercontent.com/5249598/71745508-a0f45680-2e6a-11ea-850e-e4238128d9a8.png)

**Comment by michael-hack** [comment]
I can't reproduced it. Is the issue in the current 6.1.5 still present?
