### ISSUE TITLE
Related to issue #21

### ISSUE THREAD

**Issue by JohnAherne** [Wikiki/bulma-calendar#23]
I downloaded the latest changes since I had a problem with date formats.

I use dd/mm/yyyy and the previous version would use that format to place the date in an input field.

But if I then clicked a 2nd time and brought up then calendar again it would take the date in the input field and display the calendar date as if the input field was mm/dd/yyyy. So if you had a date of 13/2/2018 the calendar would display Undefined and Null on the header and no calendar body because it treated is as mm/dd/yyyy.

But in the latest release, the format is ignored and the date placed into the input field is formatted as mm-dd-yyyy and not as dd/mm/yyyy.

Is that what is meant to happen?

**Comment by Wikiki** [comment]
Hi,

Don't forget to set the option dateFormat to dd/mm/yyyy

**Comment by JohnAherne** [comment]
Should have mentioned that. Here is my set of options

    <script> 
      document.addEventListener( 'DOMContentLoaded', function () {
        var datePicker = new DatePicker( document.getElementById( 'jobdate' ), {overlay: false,
        dataFormat: 'dd/mm/yyyy', startDate: new Date(2018,01,07)
        } );
      } );
  </script>

**Comment by Wikiki** [comment]
Actually the last update fix the dateFormat option name too (previously dataFormat)

**Comment by JohnAherne** [comment]
Didn't spot that.

However, I choose a date from the calendar and it displays as 07/02/2018. If I then click again to display the calendar, it treats the date as mm/dd/yyyy and displays July 2nd. So if I have a day 24/2/2018 I get Nulls and undefined again.

Thanks

**Comment by Wikiki** [comment]
Sorry but 24/02/2018 is not a Javascript valid date.

**Comment by JohnAherne** [comment]
When I use dd/mm/yyyy it is a valid date.

This is the date as it appears in the input box. If I leave that date there or even if I remove the date and click again, it uses the input value when it tries to display the calendar and shows the date as mm/dd/yyyy or gives null or undefined

**Comment by Wikiki** [comment]
No dd/mm/yyyy is not a valid javascript date. Try Date.parse('24/02/2018') to see it.

**Comment by JohnAherne** [comment]
OK. But what is the point of having a date format of dd/mm/yyyy.
If I use that format the date in the input box is 24/02/2018. When I click again that is the date the calendar tries to display as selected and fails.

**Comment by Wikiki** [comment]
the point is to be able for example to display date with format "mm/dd/yyyy" or "mm-dd-yyyy" for example.
For non valid Javascript date format I have to wokr on integrating a more complete date system (like moment)

**Comment by JohnAherne** [comment]
Ok. So I have to use a format using the American format not the UK format.

**Comment by Wikiki** [comment]
For now yes.
I'll work on the integration of third library to handle other date formats.

**Comment by JohnAherne** [comment]
No problem. Thanks for doing a date formatter for Bulma.
I was just trying to clarify how it worked.
