### ISSUE TITLE
Range startDate and endDate not working (for me)

### ISSUE THREAD

**Issue by phineas0fog** [Wikiki/bulma-calendar#230]
Hello :)

I made this code:

```javascript
    const options = {
      type: 'date',
      isRange: true,
      dateFormat: 'YYYY-MM-DD',
      displayMode: 'dialog',
      lang: 'fr',
    };
    
    var calendar = bulmaCalendar.attach('[type="date"]', options)[0];

    calendar.on('select', e => { console.log(e.startDate, e.endDate); });
```

And the two vars (startDate and endDate) are undefined.
But by exploring the event, I found that `e.data.datePicker.start` and `e.data.datePicker.end` are working. Is it normal or is just my code crappy ?

Thanks

**Comment by HoKangInfo** [comment]
` calendar.on('select', e => { console.log(e.data.startDate, e.data.endDate); });` can work
