### ISSUE TITLE
Bulma Losing Date On Load

### ISSUE THREAD

**Issue by jcantrel** [Wikiki/bulma-calendar#231]
**Environment**
- Extension version(s): 6.2.7
- Bulma version: .8
- OS: Windows 10 1903
- Browser: Chrome/Edge
- How you are customizing the extension: No

**Current Behavior**
I am using asp.net (aspx) to build a web page, and am loading dates from sql on page load. Then after the DomContentLoad event I am calling JS to initialize Bulma calendars. The Bulma calanders are decreasing the day on each date field by one day at load.

**Input Code**
- Initialization code:

document.addEventListener('DOMContentLoaded', function () {
            var datePickers = bulmaCalendar.attach('[type="date"]', {
                overlay: true,
                type: "date",
                showTodayButton: false,
                validateLabel: "Select"
            });
});

Without Initialization code
![image](https://user-images.githubusercontent.com/37300313/76775623-9b24c680-6773-11ea-85ac-051b7542b4bf.png)

With Initialization code
![image](https://user-images.githubusercontent.com/37300313/76775562-87796000-6773-11ea-96d3-8007455e1f75.png)

**Comment by waltersung** [comment]
Could it be timezone issue?

**Comment by jcantrel** [comment]
I am not setting a time or timezone for either field, they are pure date. It could be perhaps, but if so I have no idea why.

**Comment by jcantrel** [comment]
Working in a diffrent app, I have confirmed it does the same with MVC and Models.

**Comment by chayr** [comment]
I'm having the same issue in a django app for a datefield. My timezone is UTC-5 and the date is shifted 1 day in the past on load.

**Comment by michael-hack** [comment]
Can you please test with current 6.1.5 and give me a feedback?

**Comment by jcantrel** [comment]
It is still losing the date. The MVC Code I am using is: 

`@Html.TextBoxFor(Model => Model.DueDate, "{0:yyyy-MM-dd}", new { type = "date", required = "required", @class = "input" })`

The model is sending the date as a local DateTime (UTC -6) and as soon as I implement the javascript the displayed date changes by -1 day, without the data itself changing. I am just using the basic ES5 implementation code:

```
// Initialize all input of type date
    var calendars = bulmaCalendar.attach('[type="date"]');

    // Loop on each calendar initialized
    for (var i = 0; i < calendars.length; i++) {
        // Add listener to select event
        calendars[i].on('select', date => {
            console.log(date);
        });
    }

    // To access to bulmaCalendar instance of an element
    var element = document.querySelector('#my-element');
    if (element) {
        // bulmaCalendar instance is available as element.bulmaCalendar
        element.bulmaCalendar.on('select', function (datepicker) {
            console.log(datepicker.data.value());
        });
    }
```

**Comment by michael-hack** [comment]
Thank you I'll take a look again...

**Comment by michael-hack** [comment]
Ok, now I found the problem and fixed it. The value was treated as UTC and converted to your local timezone.
