### ISSUE TITLE
Issue Progmatically Setting Date After Init

### ISSUE THREAD

**Issue by bcorrel2** [Wikiki/bulma-calendar#237]
I am building an Angular page with the following function: when an item from a list is selected, the details of the item are populated in the fields, and the data can then be edited and saved back to the item. To put it more simply, I would like to set the fields progmatically. 

At present I am trying:

`for (calendar of this.calendars) {
       calendar.clear();
       calendar.date = selectedDate;
       calendar.startDate = selectedDate;
        calendar.save();
       calendar.refresh();
}`

but it doesn't seem to be helping. The date field is never set. Is this an issue with my code? Or a bug in the calendar?

**Comment by caffeinatedMike** [comment]
I've been struggling with being able to properly set the selected date as well. Using the below, I can get the date to update properly in the top half of the calendar, but the date doesn't show as selected in the actual calendar.

```javascript
$('#calendar-due-date')[0].bulmaCalendar.clear();
$('#calendar-due-date')[0].bulmaCalendar.date.start = new Date('06/24/2020');
$('#calendar-due-date')[0].bulmaCalendar.save();
$('#calendar-due-date')[0].bulmaCalendar.refresh();
```

**Comment by drake7707** [comment]
I managed to get it working with an inline calendar with
```
    ignoreCalenderChange = true;
    calendar.value(data.date);
    calendar.refresh();
    calendar.datePicker.refresh();
    ignoreCalenderChange =false;
```
The ignoreCalendarChange is checked in the select event because that'll be fired by the .value() call.

**Comment by gregorko** [comment]
This sequence worked for me:
```
  calendar.date.start = date;
  calendar.datePicker._visibleDate = date;
  calendar.datePicker.refresh();
  calendar.changeTimeManually();
```

**Comment by TheMaikXX** [comment]
> I managed to get it working with an inline calendar with
> 
> ```
>     ignoreCalenderChange = true;
>     calendar.value(data.date);
>     calendar.refresh();
>     calendar.datePicker.refresh();
>     ignoreCalenderChange =false;
> ```
> 
> The ignoreCalendarChange is checked in the select event because that'll be fired by the .value() call.

Hello,
thanks, refreshing the `.datePicker` motivated me to then try to manipulate the props of the `.datePicker` and that did the trick:
```
this.calendarInstance.datePicker.min = this.formatDateForDatePicker(newMinDate)
this.calendarInstance.datePicker.refresh()
```

My original issue was that using the setter: `calendarInstance.minDate = "2020/12/24"` had no effect. I also discovered that the `minDate` prop had value `NaN` without any warning/errors in the console...
(I also tried many formats and `Date` type as well)

**Comment by michael-hack** [comment]
Fixed, just use the calendar.value() method.
