### ISSUE TITLE
The calendar shows a day before the selected date

### ISSUE THREAD

**Issue by geradrum** [Wikiki/bulma-calendar#24]
When using the [demo](https://wikiki.github.io/components/calendar/#javascript) and selecting a date the calendar displays a day before the selected date.

<img width="1220" alt="captura de pantalla 2018-02-08 a la s 15 35 41" src="https://user-images.githubusercontent.com/9123134/35999716-63237cca-0ce6-11e8-8d21-5d05f0110e4f.png">

**Comment by Wikiki** [comment]
Hi,

do you have this issue only at the first time the calendar is showed or event after reopening it after having selected a date in it ?

**Comment by geradrum** [comment]
@Wikiki Both, also I found other bugs:

- I can't pass a custom `onSelect` callback option because throws an error `year, month, day` are undefined.

- If I use a custom date format and the formatted value is in the input
(e.g. dd/mm/yyyy and 01/02/2018 -> Feb 1st 2018)
when I reopen the calendar displays Jan 2nd 2018.

**Comment by Wikiki** [comment]
Hi,

ok I'll have a look on it, because I have the issue only at the first show on my side.

- for the first point: I'll merge your PR
- for the second point please see issue #27

**Comment by Wikiki** [comment]
I can't reproduce the issue you have for the one day before highlithed :-(

**Comment by geradrum** [comment]
Ok, so `onSelect` is now fixed.
I saw issue #23 and I'll try to work on a solution.
And for this issue i'm not using any configuration, can see it in the [demo](https://wikiki.github.io/components/calendar/).


If I open the calendar for the first time, the selected day is the previous from the current day.
<img width="322" alt="captura de pantalla 2018-02-10 a la s 12 39 41" src="https://user-images.githubusercontent.com/9123134/36065386-9366f18a-0e5f-11e8-8c1b-de5ba5d82c0d.png">

If I select a day, the input get the correct date but when I reopen the calendar, it show the previous day.

<img width="325" alt="captura de pantalla 2018-02-10 a la s 12 35 07" src="https://user-images.githubusercontent.com/9123134/36065407-dc4d1154-0e5f-11e8-9634-a831d9197649.png">

**Comment by Wikiki** [comment]
Not for me :'(

<img width="322" src="https://image.ibb.co/hk9LbS/Screen_Shot_2018_02_10_at_20_05_35.png">


<img width="322" src="https://preview.ibb.co/mGzLbS/Screen_Shot_2018_02_10_at_20_05_44.png">

**Comment by geradrum** [comment]
Interesting... I tested it on 3 different laptops (macbook and two Windows laptops with different browsers) same issue. I'll check the code.

**Comment by Wikiki** [comment]
Always the same issue on your side ?

**Comment by geradrum** [comment]
I don't know what changes you did but now it's working.

**Comment by Wikiki** [comment]
I can't tell 😔

**Comment by glococo** [comment]
Hi, on my proyect, when it fires onSelect event, I retrieve datepicker.element.value, but the value is the previous one.
How do I get the new value when onSelect fires ?
