### ISSUE TITLE
Date text and background are both white when range starts and ends on current date

### ISSUE THREAD

**Issue by SeanLF** [Wikiki/bulma-calendar#241]
## Bug Report

**Environment**
- Extension version(s): v6.0.0
- Bulma version: v0.7.4
- OS: macOS 10.15.4
- Browser: Firefox Dev Edition v76.0b8

**Current Behavior**
Date text and background are both `#fff` when a range starts and ends on the current date

**Possible Solution**
```css
&.datepicker-range-start.datepicker-range-end
	.date-item
		&.is-today
			color: $primary !important
```

**Comment by kevzzsk** [comment]
any workarounds for now?

**Comment by SeanLF** [comment]
@kevzzsk you could review PR #245 and see if it fixes the issue
