### ISSUE TITLE
Dummy input has 50% max-width in every case

### ISSUE THREAD

**Issue by triszt4n** [Wikiki/bulma-calendar#244]
**Is your feature request related to a problem? Please describe.**
Right now we have to accept, the dummy input allows only 50% of the input text to be shown.
Yes, this should be good enough for range datetimepickers, but not for simple ones.

**Describe the solution you'd like**
in index.sass: `.datetimepicker-dummy.datetimepicker-dummy-wrapper.datetimepicker-dummy-input` should be 100%, and maybe `&.is-datetimepicker-range` could overwrite it to 50%.

**Describe alternatives you've considered**
in index.sass: `.datetimepicker-dummy.datetimepicker-dummy-wrapper.datetimepicker-dummy-input` should have a variable for max-width, so that we can customize.

**Additional context**
![image](https://user-images.githubusercontent.com/60111772/83055539-42678900-a054-11ea-8b3f-e51db9cf7383.png)

(The svg problem is another thing happening in Chromium based browsers. Firefox can show it.)

**Comment by michael-hack** [comment]
Fixed with 6.1.2
