### ISSUE TITLE
Month names are not translated

### ISSUE THREAD

**Issue by jswale** [Wikiki/bulma-calendar#247]
## Bug Report

**Environment**
- Extension version(s): 6.0.8
- Bulma version: 0.9.0
- OS: OSX 10.15.5
- Browser: all
- How you are customizing the extension: no

**Current Behavior**
The language in the options is not used when displaying the month selection when it's something else than english

**Additional context/Screenshots**
The days of the week are translated
![image](https://user-images.githubusercontent.com/1526341/85413408-1532cb80-b56b-11ea-8106-4884b65199c0.png)

But not the short month names
![image](https://user-images.githubusercontent.com/1526341/85413336-fd5b4780-b56a-11ea-8da8-e53586917fbb.png)

**Comment by jswale** [comment]
That's inside **src/js/datePicker/templates/months.js** the month names are build.

But when the function is called, the data argument is only an array without the locale

 ![image](https://user-images.githubusercontent.com/1526341/85414974-12d17100-b56d-11ea-9ee9-e0cd54802ab2.png)

**Comment by hsson** [comment]
Swedish months are working perfectly for me when i set the "lang": "sv" option
