### ISSUE TITLE
Inline datepicker select event no longer fires

### ISSUE THREAD

**Issue by daylanv** [Wikiki/bulma-calendar#252]
Bug seems to have been introduced in commit 82ed4333c56a5861db5b3e948101ee56f710802f

Because the emit call was moved within the if statement, it no longer fires when inline calendars have their date selected. I'm able to work around the issue by directly attaching the event to the .datePicker instance, whereas previously I was able to attach the event to the bulmaCalendar instance directly.

![image](https://user-images.githubusercontent.com/50340007/87168740-2fb7b500-c28c-11ea-8b8e-2010b3cdf5e9.png)

**Comment by FrancoisYu** [comment]
Any workaround solution for this bug?

**Comment by daylanv** [comment]
It works if you reference the datepicker - i.e. instead of using calendar.on('select'), using calendar.datePicker.on('select').

I found it easier to just downgrade to 6.0.7 again.

**Comment by FrancoisYu** [comment]
For anyone looking for the solution, I've switched the date component to react-datepicker.

**Comment by affanabiyyu** [comment]
> For anyone looking for the solution, I've switched the date component to react-datepicker.

what do you mean by this?

**Comment by michael-hack** [comment]
I have also noticed the problem and I am making changes and fixing the problem shortly.

**Comment by michael-hack** [comment]
Please test the new 6.1.1, this should fix the problem.
