### ISSUE TITLE
Incorrect date time value displayed (vs what is in the input field)

### ISSUE THREAD

**Issue by rrevi** [Wikiki/bulma-calendar#256]
## Bug Report

**Environment**
- Extension version(s): 6.0.9
- Bulma version: 0.8.0
- OS: OSX 10.15.6
- Browser: Chrome 84.0.4147.125 | Safari 13.1.2 
- How you are customizing the extension: no

**Current Behavior**
The value for a datetime-local type of input field is _2020-01-09T00:00:00_ but it is displayed as _01/09/2020 00:00_ in Google Chrome and _01/08/2020 19:00_ in Safari. I was hoping it would be displayed the same as when you click on validate which is _09/01/2020 00:00_

**Input Code**
- Initialization code:

```js
const datetime_options = { type: "datetime", color: "dark", showHeader: "false" }
bulmaCalendar.attach('[type="datetime-local"]', datetime_options);
```

**Possible Solution**
First, with the same input value, the data should render/display the same. Secondly, the format of the input value should render/display the same as when you select it.

**Additional context/Screenshots**
Google Chrome:
<img width="1142" alt="google_chrome_screenshot" src="https://user-images.githubusercontent.com/1561054/90318369-fbc05700-defd-11ea-982e-d00c26ae9125.png">

Safari:
<img width="1280" alt="safari_screenshot" src="https://user-images.githubusercontent.com/1561054/90318290-a1bf9180-defd-11ea-9b38-907ec7acaae1.png">

**Comment by michael-hack** [comment]
Fixed with 6.1.2
