### ISSUE TITLE
Date Picker Not Working

### ISSUE THREAD

**Issue by graingerkid** [Wikiki/bulma-calendar#26]
Hey, 

Your example of the date picker is not working:

https://wikiki.github.io/components/calendar/

**Comment by Wikiki** [comment]
Hi,

which one ? There is 4 example on the page.

**Comment by graingerkid** [comment]
The 2 bottom ones

**Comment by Wikiki** [comment]
Do you have an error in the browser console ?
Which browser do you use ?

**Comment by graingerkid** [comment]
I mean nothing happens at all - I've not pulled this into my own environment. Your example on your site does nothing, or am I missing something?

**Comment by Wikiki** [comment]
It's working well on my side (tested on Chrome, Firefox, Safari and Opera)

**Comment by Wikiki** [comment]
Which browser do you use ? on which OS ?

**Comment by graingerkid** [comment]
chrome and chromeOS

**Comment by Wikiki** [comment]
I have no chromeOS to test :-(

**Comment by Wikiki** [comment]
I found a ChromeOS and tried and .....it's perfectly working.

**Comment by Wikiki** [comment]
Always the same issue on your side ?

**Comment by Wikiki** [comment]
Hi,

any news on your side ?

**Comment by graingerkid** [comment]
Sorry for delay.

Just tried on Windows/Chrome and it's working fine.

Tried again on ChromeOS and it's not working:
https://www.useloom.com/share/a6f424c48a8e46ed8d4870acbc002df4?focus_title=1&muted=1

**Comment by rfoel** [comment]
Tried on a ChromeOS and it works as expected.
