### ISSUE TITLE
Bulma Calendar not allowing me to create day greater than 12th

### ISSUE THREAD

**Issue by am54ful** [Wikiki/bulma-calendar#260]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [/ ] Are you running the latest version?
- [/ ] Are you reporting to the correct repository?

## Bug Report

**Environment**
- Extension version(s): [ not sure]
- Bulma version: [v6.0.9]
- OS: [Windows 10]
- Browser: [Chrome]
- How you are customizing the extension: [no]

**Current Behavior**
I try to manually adding date but it only allow date at every 12th every month. Here's my code. Date format is ` "yyyy-MM-dd"`
Working
`<input type="date" value="2020-12-12">`
`<input type="date" value="2020-11-12">`

Not working
`<input type="date" value="2020-12-26">`
`<input type="date" value="2020-12-13">`

**Input Code**
`<input type="date">`

```js
var bulmaCalendar = BulmaCalendar.attach();
var calendars = bulmaCalendar.attach('[type="date"]', type: 'date', dateFormat: 'DD-MM-YYYY');
```

**Possible Solution**
Not sure

**Additional context/Screenshots**
None

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://jsfiddle.net/0sj7pfau/

**Comment by michael-hack** [comment]
I can't reproduce it, should be fine with the newest 6.1.2
