### ISSUE TITLE
date-and-time library security vulernability

### ISSUE THREAD

**Issue by buildscientist** [Wikiki/bulma-calendar#267]
Running v5.0.3 of Bulma-Calendar but this issue is still relevant to the latest release version and code base in master. 

This library is using v0.6.3 of the date-and-time library which has a security vulnerability. See npm advisory [1592](https://www.npmjs.com/advisories/1592) for more details.

**Comment by buildscientist** [comment]
FYI - for someone who is looking to resolve this issue you can use [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions) to force bulma-calendar to use v0.14.2 or above of the date-and-time library.

**Comment by michael-hack** [comment]
Updated Library on 0.14.2

**Comment by buildscientist** [comment]
@michael-hack Thank you!
