### ISSUE TITLE
Issues with time in daterange

### ISSUE THREAD

**Issue by jesobreira** [Wikiki/bulma-calendar#269]
## Bug Report

**Environment**
- Extension version(s): 6.0.0 (?)
- Bulma version: 0.9.0
- OS: OS X
- Browser: Chrome
- How you are customizing the extension: no

**Current Behavior**
It is not possible to define the final date's time on the timerange.

Furthermore, while changing the dates fires the "select" event, changing the time doesn't, making it impossible to identify whether the time had been changed.

**Input Code**
- Initialization code:

```js
var calendar = bulmaCalendar.attach($("#daterange").get(), {
        type: 'datetime',
        isRange: true,
        dateFormat: 'DD/MM/YYYY',
        showClearButton: false,
        showTodayButton: false,
        closeOnSelect: true,
        maxDate: end,
        startDate: start.toDate(),
        endDate: end.toDate()
    })[0]

    calendar.on('select', function() {
        var startDate =calendar.startDate
        var endDate = calendar.endDate
        calendar.save()
        console.log(startDate, endDate)
    })
```

**Additional context/Screenshots**
![Kapture 2021-05-10 at 2 37 38](https://user-images.githubusercontent.com/3002249/117611081-35df2200-b139-11eb-9fca-6684ea3896c0.gif)

**Comment by ccaiuss** [comment]
The same thing happened to me. I tried for a few days to find the problem without success!! This problem also appears in the official [demo](https://bulma-calendar.onrender.com/demonstration/datetime#range-selection) !

**Comment by michael-hack** [comment]
Please test the new 6.1.1, this should fix the problem.
