### ISSUE TITLE
minDate and maxDate navigation bug

### ISSUE THREAD

**Issue by grintor** [Wikiki/bulma-calendar#275]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

- [N] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [Y] Are you running the latest version?
- [Y] Are you reporting to the correct repository?

## Bug Report

**Environment**
- Extension version(s): 6.1.10
- Bulma version: 0.9.3
- OS: Windows 10
- Browser: Chrome 92
- How you are customizing the extension: no

**Current Behavior**
When the minDate and maxDate are set, and you use the arrows to switch between months, you can become trapped in a month until you close and reopen the calendar. (see attached video)

**Input Code**
- Initialization code:

```js
var calendars = bulmaCalendar.attach('[type="date"]', {
	'type': 'date',
	'showHeader': false,
	'showFooter': false,
	'dateFormat': 'yyyy-MM-dd',
	'minDate': moment().subtract(30, 'days').format('YYYY-MM-DD'),
	'maxDate': moment().format('YYYY-MM-DD'),
	'startDate': moment().format('YYYY-MM-DD'),
	'enableYearSwitch': false,
	'enableMonthSwitch': false,
	
});
```

Video of the problem:
https://recordit.co/M5mWjdt3jN

**Comment by michael-hack** [comment]
Thank you, should be fixed.
