### ISSUE TITLE
Build failure in 6.1.11 and 6.1.10

### ISSUE THREAD

**Issue by JoshClose** [Wikiki/bulma-calendar#276]
I updated to `6.1.11` and get an error. This error also occurs in `6.1.10`, but is not present in `6.1.9`.

```
Uncaught Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @import "../../node_modules/bulma/sass/utilities/controls.sass"
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\bulma-calendar\src\sass\index.sass 1:9  @import
```

The project was created using `create-react-app`.

- bulma 0.9.3
- sass 1.37.5
- react-scripts 4.0.3

**Comment by michael-hack** [comment]
"npm run build" and "gulp build" runs fine here. Did you run "npm install" after update?

**Comment by JoshClose** [comment]
Check out this reproduction of the issue. https://github.com/JoshClose/bulma-calendar-issue

Just run
```
npm install
npm run start
```

**Comment by latica-jp** [comment]
Same here, thanks @JoshClose saved my time.

**Comment by michael-hack** [comment]
Thank you, the penny has dropped.

I replaced the relative import paths to ~bulma in 6.1.12

**Comment by JoshClose** [comment]
Thanks!
