### ISSUE TITLE
Localization to Croatian language is wrong and incomplete

### ISSUE THREAD

**Issue by dmcbrn** [Wikiki/bulma-calendar#281]
## Bug Report

**Environment**
- Extension version(s): 6.1.12
- Bulma version: 0.9.3

**Current Behavior**

![Screenshot from 2021-09-21 13-40-04](https://user-images.githubusercontent.com/40859618/134164502-8723fc67-a355-4e97-b4f2-9f961b46cac6.png)

The translations for names of the months are wrong.
The translations for today/clear/cancel are not there.

**Possible Solution**

I've checked the [date-fns](https://github.com/date-fns/date-fns/blob/master/src/locale/hr/_lib/localize/index.js) library and you should use `monthValues` instead of `formattingMonthValues`.
I don't know in details how this all works but the translation is in the wrong "case of the noun" (I hope that's the correct translation and the `monthValues` will provide the right case. I'm not sure will this affect other languages so maybe you could provide another options.attribute to select whether to use `monthValues` or `formattingMonthValues`.

The hr translaations for today/clear/cancel could be danas/poništi/odustani but I don't know where to put these.

**Comment by michael-hack** [comment]
Thank you for your efforts.

I need to take a closer look, but I think you might be right about the month names and that the wrong value is used there.

Regarding the footer buttons, there is no translation, you have to change that yourself in the config. Have a look at the values cancelLabel, clearLabel and validateLabel in https://doc.mh-s.de/bulma-calendar/#options.

**Comment by dmcbrn** [comment]
Thanks!

Regarding the translations in the footer. To be honest I didn't, I just glanced the options and wrongly assumed this is somehow connected to the translations issue above. Thanks for pointing that out!

**Comment by michael-hack** [comment]
Fixed in 6.1.13
