### ISSUE TITLE
I want to change the weekday label

### ISSUE THREAD

**Issue by zhixXiang** [Wikiki/bulma-calendar#283]
I want to change the type of weekday label to 'ccccc', can you make it as parameter in option that i can replace it mysefl?
`
// the 7 days of the week (Sun-Sat)

        const weekdayLabels = new Array(7).fill(dateFns.startOfWeek(this._visibleDate, {weekStartsOn: this.options.weekStart})).map((d, i) =>
            dateFns.format(dateFns.addDays(d, i), 'ccc', { // i want to change this
                locale: this.locale,
            })
        );
`
Thank you

**Comment by michael-hack** [comment]
I can change it the next days...
