### ISSUE TITLE
Cutsom year format

### ISSUE THREAD

**Issue by zhixXiang** [Wikiki/bulma-calendar#287]
**Is your feature request related to a problem? Please describe.**

Does this calendar support custom year? I want to use my country's year, not use C.E.

Maybe there is a function that i can coding the parsing rule by myself.

**Comment by michael-hack** [comment]
I'm not sure what you mean with custom year... you can set the locale and the date format with the options "lang" and "dateFormat" with values from date-fns 2.x.

Does this help or do you need something else?

Documentation: https://doc.mh-s.de/bulma-calendar/#options

**Comment by zhixXiang** [comment]
Thank you for quick response.
Our country's year is C.E year - 1911,  for example, this year is 2021, our year is 110
So I need to show 110 on calendar, not 2021, is it possible?

**Comment by zhixXiang** [comment]
> I'm not sure what you mean with custom year... you can set the locale and the date format with the options "lang" and "dateFormat" with values from date-fns 2.x and also the year format in the navigation header with "formats.header" and "formats.navigationYear" and in the year selection with "formats.selectYear".
> 
> Does this help or do you need something else?
> 
> Documentation: https://doc.mh-s.de/bulma-calendar/#options

Thank you for quick response.
Our country's year is C.E year - 1911, for example, this year is 2021, our year is 110
So I need to show 110 on calendar, not 2021, is it possible?

**Comment by michael-hack** [comment]
Unfortunately, I don't know anything about this, but I'm not a date-fns specialist. Since the whole display and formatting is based on the date-fns library, I think you should ask there if this is possible.

If this would require some adjustments in the calendar, I would be happy to make them.
