### ISSUE TITLE
Today button is not working in v6.1.17, v6.1.18

### ISSUE THREAD

**Issue by autumninflab** [Wikiki/bulma-calendar#304]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [x] Are you running the latest version?
- [x] Are you reporting to the correct repository?

## Bug Report

**Environment**
- Extension version(s): 
- Bulma version: v6.1.17
- OS: [e.g. OSX 10.13.4, Windows 10]
- Browser: all
- How you are customizing the extension: no

**Current Behavior**
Today button is not working.
https://doc.mh-s.de/bulma-calendar/demonstration/date/#range-selection

**Comment by michael-hack** [comment]
Happend in range selection only. Is fixed with next release.
