### ISSUE TITLE
Broken link to the documentation page in the Readme

### ISSUE THREAD

**Issue by Krzyshio** [Wikiki/bulma-calendar#313]
- [x] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [x] Are you running the latest version?
- [x] Are you reporting to the correct repository?

## Bug Report

**Environment**
- Bulma version: [ v6.1.18 ]
- OS: all
- Browser: all

**Current Behavior**
When clicking on the link to the documentation page in the repository, the user is taken to a page that returns a 404 error.

**Possible Solution**
A possible solution would be to update the link in the repository to point to the correct documentation page. 
`https://bulma-calendar.onrender.com/`

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/44636754/218253511-f4be2e53-ba0a-4479-8526-ab89fa41e246.png)

![image](https://user-images.githubusercontent.com/44636754/218253426-d344363c-025a-4cba-8c51-769d6c350ec9.png)

**Comment by michael-hack** [comment]
Sorry, a small DNS issue after a server switch. The specified URL https://doc.mh-s.de/bulma-calendar/ is the current version and should be available again in the next few hours (DNS distribution). The other URL and documentation is outdated.
