### ISSUE TITLE
Datepicker buttons do not display properly without Font Awesome 4

### ISSUE THREAD

**Issue by moenth** [Wikiki/bulma-calendar#34]
The buttons to change month and year reference FA icons directly in the template. As a result they will not display properly if these icons are not available.

Perhaps a stand-alone CSS or SVG solution could be used instead?

**Comment by Wikiki** [comment]
Hi,

Good idea.
Don't hesitate to propose standalone css or svg if you found them ;-)

**Comment by Wikiki** [comment]
Done.
