### ISSUE TITLE
Uglify Errors

### ISSUE THREAD

**Issue by rmaspero** [Wikiki/bulma-calendar#36]
I'm trying to include this with my rails app and it repeatedly fails sprockets tries to compile. It appears to be an issue when running uglify to minify the code.

**Comment by Wikiki** [comment]
Hi,

The code follows ES6, so you can't use uglify. See my gulpfile.js to see which plugin I use to minify the code.

**Comment by mark100net** [comment]
You can configure uglify with ES6 as noted [in the uglifier gem readme](https://github.com/lautis/uglifier)

I am getting 

    NoMethodError: undefined method `start_with?' for nil:NilClass`

when running 

    rails assets:precompile

**Comment by Wikiki** [comment]
@mark100net thanks for the information. I didn't know that.
I'll a have a look to your issu. Can you please provide the line where the issue appears ?

**Comment by mark100net** [comment]
@Wikiki Sorry I can't be much help on this. I switched to a different calendar solution but as I recall I was unable to determine exactly where the error was triggered. I got no other info than the error message. I only was able to attribute it to this gem by process of elimination.
