### ISSUE TITLE
Unable to use the calendar as input

### ISSUE THREAD

**Issue by HerrEisenheim** [Wikiki/bulma-calendar#37]
In a new laravel project, I installed bulma-calendar using `npm install bulma-calendar --save-dev`. In my app.scss file, I am importing both bulma and bulma-calendar like this:

```
@import "~bulma";
@import "~bulma-calendar";
```
and in the bootstrap.js file at the top of the file I imported the minified js file:

```
import bulmaCalendar from 'bulma-calendar/dist/bulma-calendar.min.js'
```

and at the bottom of it I added this:

```
document.addEventListener( 'DOMContentLoaded', function () {
  var datePicker = new bulmaCalendar( document.getElementById( 'datepickerDemo' ), {
    startDate: new Date(), // Date selected by default
    dateFormat: 'yyyy-mm-dd', // the date format `field` value
    lang: 'en', // internationalization
    overlay: false,
    closeOnOverlayClick: true,
    closeOnSelect: true,
    // callback functions
    onSelect: null,
    onOpen: null,
    onClose: null,
    onRender: null
  } );
  var datePicker = new bulmaCalendar( document.getElementById( 'datepickerDemo2' ), {
    overlay: true
  } );
} );
```
And in my welcome.blade.php I added an input element:

```
<input id="datepickerDemo" class="input" type="text" value="11-02-2018">
```

But I don't see any calendar when I click on that input field, just as I see on your demo page. What am I missing?

**Comment by Wikiki** [comment]
Hi,

you do'nt have to use <code>import bulmaCalendar from 'bulma-calendar/dist/bulma-calendar.min.js'</code> just include js file in your html and call <code>var datePicker = new bulmaCalendar( document.getElementById( 'datepickerDemo' ));</code>

**Comment by HerrEisenheim** [comment]
I am in a laravel project and it's a common practice that a dependency (like bulma-calendar) should be pulled in through npm and all of the js files are bundled to a single app.js file. But you are asking me to hardcode the script src which is a bit odd :(

**Comment by Wikiki** [comment]
I'm not a laravel developer sorry if my idea was odd in this context 😉

**Comment by HerrEisenheim** [comment]
I am also seeing this error in the console:
`TypeError: __WEBPACK_IMPORTED_MODULE_0_bulma_calendar_dist_bulma_calendar_min___default.a is not a constructor`

**Comment by Wikiki** [comment]
Have you tried importing the non minified version ?

**Comment by HerrEisenheim** [comment]
I tried importing non minified version. No luck. Not sure if I fetched the latest version, but I re-installed bulma-calendar (1.1.1) and tried again, but still that TypeError in the console...

**Comment by Wikiki** [comment]
last version (integrating the new transpilation format) is 1.1.2

**Comment by HerrEisenheim** [comment]
Apologies for delayed response. Yes it works now. But the navigation buttons look huge. Take a look: https://imgur.com/a/8YcY4

**Comment by Wikiki** [comment]
Yes they are huge. It's weird. I'll see that

**Comment by HerrEisenheim** [comment]
@Wikiki when I inspect element on the demo site (https://wikiki.github.io/components/calendar/) I can see a font awesome class. But in your latest release, that icon element is replaced by some svg stuff... Thought I should share the info with you so you can hunt down the source of the problem...

**Comment by Wikiki** [comment]
Thanks for the hint 😉

**Comment by Wikiki** [comment]
I updated the demo site and SVG have the good size on it.
But I see I have the following css rule you don't seem to have on your side:
```
svg {
    max-height: 100%;
    max-width: 100%;
}
```

**Comment by kaizermd** [comment]
Buttons aren't visible on the demo site. 
![image](https://user-images.githubusercontent.com/32821416/36560561-bdbf512a-1819-11e8-9c7b-660c599ee9b2.png)

**Comment by Wikiki** [comment]
Which browser to you use ?

**Comment by Wikiki** [comment]
Fixed
