### ISSUE TITLE
Year buttons not appearing

### ISSUE THREAD

**Issue by pelted** [Wikiki/bulma-calendar#40]
@kaizermd mentioned this in #37 but it is a separate bug.

I first noticed the missing buttons when I implemented the calendar on a test form. They also do not appear in the demo site. Overlay also makes no difference.

Tested with:

* Safari 11.0.3
* Chrome Version 64.0.3282.186

**Comment by pelted** [comment]
Just noticed #34 that was closed and commit 1d7c1f6 which is the cause of the regression. Since Bulma provides support for: 

* Font Awesome 5
* Font Awesome 4
* Material Design Icons
* Open Iconic
* Ionicons

Maybe a better solution would be to allow the user to pass an `iconSet` set property to the constructor. Then the the JS can handle switching out the icons based on the chosen set. This way the UI stays uniform to the users website icon choices with out making assumptions with FA, or even embedded SVG.

If interested I could do a PR for this change.

**Comment by Wikiki** [comment]
Hi @pelted,

Great idea. I'm interested by a PR for that.

Regards

**Comment by Wikiki** [comment]
Your PR has been integrated.
Thank you ;-)
