### ISSUE TITLE
cant find arrows

### ISSUE THREAD

**Issue by steinryan** [Wikiki/bulma-calendar#42]
I can not find month and year change arrows in last two examples [https://wikiki.github.io/components/calendar/](url).

update
And I used fontawesome 5 with this

```
const datePicker = new bulmaCalendar(document.getElementById( 'b-cal' ), {
       iconSet: 'fontawesome-5',
       overlay: true,
       dateFormat: 'dd/mm/yyyy',
    });

```

but still not working

**Comment by Wikiki** [comment]
Hi,

did you include Fontawesome 5 css into your html page ?
The extension does not include any icon set.

regards,

**Comment by andreujuanc** [comment]
Can you publish this fix in npm? thanks!!!
