### ISSUE TITLE
maxDate not working

### ISSUE THREAD

**Issue by NuruddinBadawi** [Wikiki/bulma-calendar#43]
I can't add maxDate, I add to the options the following code.
```
maxDate: new Date(),
```

**Comment by Wikiki** [comment]
Please provide a working codepen. Becaus I can't reproduce this issue (the documentation page use it and it's working fine : see last overlay demo)

**Comment by erik888** [comment]
If you don't add a minDate it won't work. Just add:
minDate: new Date(1900,1,1)

**Comment by erik888** [comment]
Within _renderdays should be:
if (day.getMonth() !== this.month || (this.options.minDate &&
        day.getTime() < this.options.minDate.getTime()) || (this.options.maxDate && day.getTime() > this.options.maxDate.getTime())) {
        isDisabled = true;
      }

**Comment by Wikiki** [comment]
@erik888: thanks for the fix.
It has been integrated into v1.3.0
