### ISSUE TITLE
Touch devices vs nontouch

### ISSUE THREAD

**Issue by andreujuanc** [Wikiki/bulma-calendar#47]
Hello!, i'm testing this component for a project and I found couple of stuff. Each will have it's own separate issue.

Also, if I have time, ill do the PR myself, but i always prefer to discus it here and introduce myself.

Ok, so, in source code I found:
`
this._clickEvent = ('ontouchstart' in window) ? 'touchstart' : 'click';
`

Which it's ok, but in a laptop with touchscreen does not play well if user is interacting with mouse.

I implemented this: 

`
   Element.prototype.addEventsListener = function(events, listener) {
      if(!Array.isArray(events))
        events =[events];
      for(let i = 0; i<events.length; i++)
        this.addEventListener(events[i], listener);
    }

    this._clickEvent = ['touchstart' , 'click'];
`
and replaced all addEventListener with addEventsListener. It works.

**Comment by Wikiki** [comment]
Hi,

I did not thought about touchscreen computers ☹️.
I'll integrate your idea.

Thanks

**Comment by Wikiki** [comment]
Fixed with commit #ded99e8

I'll update npm soon.
