### ISSUE TITLE
Consider using UMD by default

### ISSUE THREAD

**Issue by andreujuanc** [Wikiki/bulma-calendar#48]
For some projects importing all file and bundling is important. 

So it'd be nice if jsFormat = false so umd can be use by default when importing from npm.

EDIT: Forgot to say the second option. Publish the source in NPM. :) meanwhile comes from github.

It makes more sense that people using npm to use this project also uses some kind of bundler.

Let me know what you guys think about this. 

Cheers!

**Comment by Wikiki** [comment]
Umd by default sound fine to me.
You have great ideas 😀. Thanks a lot.
