### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by bcarneiro** [Wikiki/bulma-calendar#50]
Can you please explain how to add events to the calendar?
Thank you.

**Comment by Wikiki** [comment]
Hi,

you can use one of the following callback definition when instantiating a new calendar:
- onSelect : function(SelectedDate)
- onOpen: function(CalendarInstance)
- onClose: function(CalendarInstance)
https://wikiki.github.io/components/calendar/

**Comment by stevensacks** [comment]
This is not working for me.

```javascript
componentDidMount() {
    bulmaCalendar.attach(`#date-picker-${this.props.version.id}`, {
        overlay: true,
        startDate: this.props.version.releaseDate,
        onSelect: this.onDateSelect,
    });
}

onDateSelect = event => {
    console.log('onDateSelect', event);
};
```

My callback doesn't get called.

Further, I dug into the source code and there's nothing in there that would call onSelect or any callback by any name you listed above. There's no reference to onSelect, onOpen or onClose.

The input field onChange doesn't fire, either. And when I check the input element's value using Javascript, it's stuck at its original value.

It's entirely unclear how to actually get the value that the calendar picker selected, and there's nothing in the docs that tells you how to get it.

**Comment by leandrowilliam** [comment]
The event `"date:selected"` is triggered twice when I select a date 🤔

**Comment by zez9787** [comment]
The event is firing twice because anytime the function ```this.value()``` is called it will emit a date:selected event. I'm not sure if that was by design or it's a possible bug.
