### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by arhont375** [Wikiki/bulma-calendar#52]
Hi, 
When I tried to use your library with webpack I met problem, that ` $radius-small` is not defined, when I tried to bundle it with `node-sass` loader.
I found that if you sass module have dependencies from other npm package you need to use special tilde import to define dependencies, so it will be possible to load modules in right order.

In case of `bulma-calendar` it was needed to add `@import "~bulma/bulma"` on top line of `bulma-calendar.sass`, after that I was able to bundle `bulma-calendar` with webpack without problem.

Can you take a look into this problem?
Anyway thanks for great library!

Sorry can't find in doc about this import, but it defined somewhere in this package: https://npmjs.org/package/node-sass
And link to discussion about implement this: https://github.com/sass/sass/issues/2350

**Comment by Wikiki** [comment]
Hi,

as mentioned in the documentation : extensions requires Bulma to be installed first.
It's extension and they are not self-sufficient

**Comment by arhont375** [comment]
@Wikiki  Hi, Bulma was installed first as well.

This application doesn't have sass files to import, to make it like in documentation. And it's not needed now.
But module was imported to use it in javascript code.
Later, during webpack build I faced problem that I described above.

Can you check this one more time? Or I can provide link to repository where it can be rerpoduced, if it's needed

**Comment by Wikiki** [comment]
If you installed bulma first tyen how do you import it ? Using css ? If yes then import the css extension file (by default it's the sass file but if you use the import rule using css file existing into dist folder then it'll work)

**Comment by seanodotcom** [comment]
+1 Having this issue too, as I'm trying to get any bulma-calendar JavaScript working.

**Comment by Wikiki** [comment]
Did you import Bulma first ?

**Comment by Ninos** [comment]
Hey @Wikiki have the same problem. I get following error loading bulma-calendar with webpack:
`ReferenceError: bulmaCalendar is not defined`

My testing code looks something like this:
```
require('bulma-extensions/bulma-calendar/dist/bulma-calendar.js');

document.addEventListener('DOMContentLoaded', function () {
    var date = new bulmaCalendar(document.querySelector('.sr-date'), {
        dataFormat: 'd MM yyyy'
    });

    var datePickers = bulmaCalendar.attach('[type="date"]', {
        overlay: true,
        minDate: '2018-01-01',
        maxDate: '2018-12-31',
        dateFormat: 'yyyy-mm-dd'
    });
});
```

Any solutions?

**Comment by Wikiki** [comment]
Hi, sorry for the inconvenience I'll fix this issue this weekend.

**Comment by Wikiki** [comment]
Hi,

please use the v2.0.0

**Comment by mokhosh** [comment]
thanks for your quick answer. it would be nice to be able to import it without referencing the file. bulma-switch does that now:
```
@import "~bulma-switch";
```

i still can't import the js. can we add these to the documentation please?

**Comment by Wikiki** [comment]
bulma-switch only have sass so it's easy to make a shortcut for inclusion. For extensions with both (sass and JS) I don't know how to do it into the package.json file

**Comment by Ninos** [comment]
Changed to v2.0.0 and 2.0.1, still with same problems...
.scss:
```
// Import the rest of Bulma
@import "~bulma/bulma";
// Import Bulma Extensions
@import "~bulma-calendar/dist/css/bulma-calendar";
```

.js:
```
require('bulma-calendar/dist/js/bulma-calendar.js');

document.addEventListener('DOMContentLoaded', function () {
    var date = new bulmaCalendar(document.querySelector('.sr-date'), {
        dataFormat: 'd MM yyyy'
    });

    var datePickers = bulmaCalendar.attach('[type="date"]', {
        overlay: true,
        minDate: '2018-01-01',
        maxDate: '2018-12-31',
        dateFormat: 'yyyy-mm-dd'
    });
});
```

package.json:
```
 "dependencies": {
        ...
        "bulma": "^0.7.1",
        "bulma-calendar": "^2.0.0",
        "bulma-extensions": "^1.0.14",
        ...
}
```

**Comment by crabnky** [comment]
Have the same issue - any solutions?

**Comment by mokhosh** [comment]
this has worked for me:
```js
import bulmaCalendar from 'bulma-calendar/dist/js/bulma-calendar.min'
```
```scss
@import "~bulma-calendar/dist/css/bulma-calendar.min.css";
```

**Comment by Wikiki** [comment]
Sorry for the inconvenience, I don't find the proper way to package the extension to work with: require() / import / <script></script>
If anyone as any clue don't hesitate to share.

And secondly I don' know how to be able to mis both .js and .sass or .css when including. Package.json only accepts one main entry point at a time.

**Comment by Wikiki** [comment]
thanks @mokhosh

**Comment by mokhosh** [comment]
Take a look at this. I haven't tried it, I just came across it and thought it might help from the looks of its readme:

https://github.com/lucasmotta/sass-module-importer

**Comment by keithgulbroIT** [comment]
Hi All,

I had an issue importing some of the bulma components inside my main SASS stylesheet. The random workaround I used looks as follow:

```
@import '~bulma/bulma.sass';

@import '~bulma-accordion';
@import '~bulma-switch';
@import '~bulma-tooltip';
```

Notice that the first import is the Bulma CSS framework followed by any additive components in alphabetical order. For some reason, if I were to swap the placements of `bulma-accordion` & `bulma-tooltip` an error would be thrown in my console.

Hopefully this helps!
