### ISSUE TITLE
unable to use bulma extension (calender) with laravel 

### ISSUE THREAD

**Issue by saraElsanan** [Wikiki/bulma-calendar#53]
i did the instructions in WIKI , i used npm run because i use laravel , then i integrated the calender extension in bulma.js in the assets folder

`import 'bulma-extensions/bulma-calendar/dist/bulma-calendar.js';`

then i used `npm run dev`  and it was build successfully 
but when i use the initialization function 
```
<script type="text/javascript">
        var date = new bulmaCalendar(document.querySelector('.calendar'), {
          dataFormat: 'd MM yyyy' // 1 January 2018
        });
</script>
```
i got error in console   `Uncaught ReferenceError: bulmaCalendar is not defined`

![1](https://user-images.githubusercontent.com/11338871/38467422-9adf8fe8-3b38-11e8-8c02-faffac6dd038.png)
![2](https://user-images.githubusercontent.com/11338871/38467423-9b0d0b3a-3b38-11e8-863f-59feb1455f14.png)
 so why i got this error even if the code is already inserted .... any help please

**Comment by saraElsanan** [comment]
i really don't get it ... when i use the script in the normal way it works just fine .. but when i use laravel mix ... i got this error

**Comment by saraElsanan** [comment]
@victormongi   i used https://github.com/vue-bulma/datepicker and it works just fine with laravel mix ... but install sass and stulyes first 
`npm install stylus stylus-loader style-loader --save-dev`
`npm install node-sass sass-loader`

and then install datepicker 
`npm install vue-bulma-datepicker --save`

and then import them in app.js

**Comment by Wikiki** [comment]
Hi,

I'm know there is issues with laravel integration.
I'm trying to find someone to help me on it: https://github.com/Wikiki/bulma-extensions/issues/30

**Comment by Wikiki** [comment]
Hi, 

please use Bulma + extension package here https://github.com/laravel-frontend-presets/bulma maintained by @Laraveldeep

**Comment by bobking256** [comment]
I tried using Bulma + extension package and for some reason bulma-calendar is not working, at least for me.  I spent way too many hours trying to get it to work.  I ended up including js file in the main layout page and including javascript within the blade.  It worked... mostly.  For some reason after picking a date and re-opening the calendar, it shows up a day earlier.  I think this is a bug fixed in the latest version.  Unfortunately when I include the latest version, it won't compile.  I have reached out to developer to see how to resolve.

**Comment by happy199** [comment]
Hello i'm use laravel 6 and i had the same issue. But i found a way to resolve it and now bulma calendar work perfectly in my project.

/resources/sass/app.scss
`// Import component
@import "bulma-calendar";`
/resources/js/app.js : 
put this on top
`var bulmaCalendar=require('bulma-calendar');`
after this : 
`document.addEventListener('DOMContentLoaded', function () {

        
    // Initialize all input of type date
    var calendars = bulmaCalendar.attach('[type="date"]', []);

    // Loop on each calendar initialized
    for(var i = 0; i < calendars.length; i++) {
        // Add listener to date:selected event
        calendars[i].on('select', date => {
            console.log(date);
        });
    }

    // To access to bulmaCalendar instance of an element
    var element = document.querySelector('#my-element');
    if (element) {
        // bulmaCalendar instance is available as element.bulmaCalendar
        element.bulmaCalendar.on('select', function(datepicker) {
            console.log(datepicker.data.value());
        });
    }
});`

in my view blade.php
`<input type="date">`

It's work for me i hope that it will help you
