### ISSUE TITLE
How to use full-size calendar with javascript?

### ISSUE THREAD

**Issue by seanodotcom** [Wikiki/bulma-calendar#54]
I'm trying to get JavaScript working with bulma-calendar, and not finding much success.

I've started a new vue-cli project, and have installed bulma & bulma-calendar using npm. I can get the CSS loaded with
`import '../node_modules/bulma/css/bulma.css';`
in _App.vue_, and
`<style src="../../node_modules/bulma-calendar/dist/bulma-calendar.min.css"></style>`
in my custom component, and it _looks_ fine.

However, when I try to get it to _work_ by adding
`import bulmaCalendar from "../../node_modules/bulma-calendar/dist/bulma-calendar.min.js`
in my component, I get tons of
`[Vue warn]: Property or method "..." is not defined on the instance but referenced during render.` errors in the console.

I've setup a custom _BulmaCalendar.vue_ component with the following structure:
```
export default {
  name: 'MyBulmaCalendar',
  data() {
      return {
        fullSize: true,
        events: [...] // pulled in from API
      }
  },
  methods: {
    // chevron buttons
    prevMonth() {...},
    nextMonth() {...}
  }
}
```

Q1: How can I get the bulma-calendar JS working?
Q2: How can I add my own data & methods?

**Comment by Wikiki** [comment]
Hi,

the full-size calendar is not yet handled by javascript.
It will in the next release coming soon.
