### ISSUE TITLE
Fail to minify into react-create-app

### ISSUE THREAD

**Issue by aureliome** [Wikiki/bulma-calendar#55]
Hi,
congratulations for your job with Bulma-Calendar component, it's great!

I have an issue with react-create-app build and bulma-calendar library.

I import it in this way

 	import bulmaCalendar from 'bulma-calendar/dist/bulma-calendar';

and it works correctly on development environment (_npm run start_ or _react-scripts start_).

But if I try to make a build of the application (_npm run build_ or _react-scripts build_), the build process return this error:

 	Failed to minify the code from this file:
 	./node_modules/bulma-calendar/dist/bulma-calendar.js:178
 	Read more here: http://bit.ly/2tRViJ9

In that link is reported:

`To resolve this:
Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled.
Note: Create React App can consume both CommonJS and ES modules. For Node.js compatibility, it is recommended that the main entry point is CommonJS. However, they can optionally provide an ES module entry point with the module field in package.json. Note that even if a library provides an ES Modules version, it should still precompile other ES6 features to ES5 if it intends to support older browsers.`

Can we do anything to resolve it?
Thanks
Aurelio

**Comment by Wikiki** [comment]
Hi,

This is due to the minify engine.
In dist directory you can find a pre-minified version.

Regards

**Comment by Wikiki** [comment]
For information on my side I use <code>gulp-babel-minify</code> module to minify the source.

**Comment by rupps9800** [comment]
Have same issue es6 but need es5 when making production build. Perhaps a es5 version would be accommodating for some of us.

**Comment by Wikiki** [comment]
Hi, don't hesitate to modify package.browsers rule and compile it using gulp to get a ES5 working version ;-)

**Comment by stevensacks** [comment]
@aureliome @rupps9800 

I rewrote this lib from the ground up for use in React, leveraging his great SASS styling, but made specifically for React.

I've open-sourced the code here:
https://gist.github.com/stevensacks/79c60d0f8b1f8bc06b475438f59d687e

Note that my implementation uses my Dialog as a Promise component, which is also open-source (and linked to). You can use that also if you like. But if you don't, you're free to modify DatePicker.js to use whatever methodology you prefer. This is why I haven't turned it into standalone "npm install" library.

Hope you find it useful!

**Comment by devth** [comment]
Would be awesome to get a React component up on npm for this!
