### ISSUE TITLE
Problem with multiple calendar instances

### ISSUE THREAD

**Issue by tanmay-das** [Wikiki/bulma-calendar#56]
The documentation suggests that we create a calendar by instantiating the `bulmaCalendar()` constructor. Like this:
```
   var datePicker = new bulmaCalendar( document.getElementById( 'datepickerDemo' ), {
        overlay: true
    });
```
The problem is, what if my application requires 50 calendars? Do I have to instantiate the `bulmaCalendar()` constructor for each of them? This could be solved by allowing users to pass an array of "elements" (`document.getElementsBy*` or `document.querySelectorAll()`) instead of just a single "element" (`document.getElementBy*`). As a temporary solution, I tried this:

1. I gave each of my inputs a class name: `datepicker`
2. In JS, I fetched all those elements with that class in an array: `datepickersall`.
3. I iterated over that array and for each of the elements, I instantiated `bulmaCalendar()`.

```
document.addEventListener( 'DOMContentLoaded', function () {
    var datepickersall = document.querySelectorAll('.datepicker');
    Array.prototype.forEach.call(datepickersall, function(elem){
        console.log(elem);
        new bulmaCalendar(elem, {
            overlay: true
        });
    });

    /*var datePicker = new bulmaCalendar( document.getElementById( 'datepickerDemo' ), {
        overlay: true
    });*/
} );
```
And in the HTML:
```
<input class="input datepicker" type="text">
...
<input class="input datepicker" type="text">
```

Sadly, it didn't work. What can I do about it?

**Comment by Wikiki** [comment]
Hi @tanmay-das,

your code looks good....I'll run some tests on my side and let you know
