### ISSUE TITLE
Undefined variable: "$radius-small"

### ISSUE THREAD

**Issue by Kaisaurus** [Wikiki/bulma-calendar#58]
Hi, first of all thanks for this awesome project.
I just wanted to report a error I am getting when compiling.

My sass import looks like this:
```
@import "~bulma"
@import '~bulma-calendar'

```
I am using:

```
"bulma": "^0.6.0",
"bulma-calendar": "^1.3.0",

```
I am getting this error (I use GatsbyJS/React): 
```
 ERROR  Failed to compile with 1 errors

 error  in ./~/bulma-calendar/dist/bulma-calendar.sass

Module build failed:
$calendar-border-radius: $radius-small !default
                        ^
      Undefined variable: "$radius-small".
```

**Comment by yurfuwa** [comment]
I happened same problems on nuxt.js :S

**Comment by Kaisaurus** [comment]
I found out the problem was in the way I imported in the .js file, not the sass import.

I used to have a import like such 
`import bulmaCalendar from 'bulma-calendar`

This imported the .js and the .sass which was giving the error, changing the import to the following fixed the error:
`import bulmaCalendar from 'bulma-calendar/dist/bulma-calendar.min'`

(Im still importing the sass the same way as before)
`@import "~bulma"
@import '~bulma-calendar'`

**Comment by Wikiki** [comment]
Hi,

it's a weird behavior that sass trigger an error.

@Kaisaurus thanks, I'll update the doc with your fix
