### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by JCardoen** [Wikiki/bulma-calendar#63]
Hello.

I have a question regarding the implementation of a display calendar to show dates on which appointments have been planned.

I cannot find more info in the documentation.

I want to show a small calendar which can be navigated and where I can dynamically insert dates using js.

What is the correct implementation for that as I can't seem to find it anywhere.

Thanks in advance.

**Comment by Wikiki** [comment]
Hi,

currently only datePicker is implemented.
Feel free to code your own behavior for just display.

I'll work on small and full-calendar management but there is not ETA now.
