### ISSUE TITLE
ie11 Element.prototype.addEventsListener error 

### ISSUE THREAD

**Issue by alphabravo8** [Wikiki/bulma-calendar#66]
Hello,

bulma-calendar version 1.1.9

Very good calendar but facing a bit of a problem with my ie11 users,  ie11 console is complaining about bulma-calendar.js:169:65 with:

    Element.prototype.addEventsListener = function(events, listener = void 0) {

    window.onerror
    Expected ')'

Any idea how I could get around this would be appreciated.

Thank you

**Comment by Wikiki** [comment]
I'll have a look.
