### ISSUE TITLE
Button hover is broken

### ISSUE THREAD

**Issue by fariasfrancisco** [Wikiki/bulma-calendar#7]
After I press one of the buttons to change the month, the button inverts its hover colors.

By this I mean that if I click the button then when I leave the button, the button will appear hovered and when I hover it it will appear normally.

**Comment by fariasfrancisco** [comment]
Let me know If you need a video of it or something

**Comment by Wikiki** [comment]
It'll be helpful to have a video. Thanks

**Comment by fariasfrancisco** [comment]
there you go
https://www.youtube.com/watch?v=8BjFHH7qVCA&feature=youtu.be

**Comment by Wikiki** [comment]
Sorry but I don't really see the point on your video.

It seems you made some improvment to add the possibility to manually enter the date instead of going through all years.
Can you share this code to be able to test it on my side ?

**Comment by fariasfrancisco** [comment]
Sorry, thats the wrong video. Here is the right one [VIDEO](https://www.youtube.com/watch?v=8BjFHH7qVCA&feature=youtu.be)
As soon as I finish my component I will share the code =D.

**Comment by Wikiki** [comment]
Sorry but I can't reproduce this behavior on my side.
Are you sure you're using the last version ?

**Comment by fariasfrancisco** [comment]
Yup, must be css on my side, don't worry. If I figure it out I will tell you.

**Comment by Wikiki** [comment]
Thanks.
For notice the new buttons use <code>is-text</code> instead of <code>is-link</code> due to the last updates of Bulma.

**Comment by Wikiki** [comment]
Hi,

do you still having issue ?

**Comment by fariasfrancisco** [comment]
Hey, not really. I mean I fixed it but I don't recall the exact part
I will publish my component as an angular directive and I will link you to it soon enough.
