### ISSUE TITLE
Consider using Rollup for building

### ISSUE THREAD

**Issue by andreujuanc** [Wikiki/bulma-calendar#78]
Hi !

Have you consider this? It's remarcably faster for dev and uses babel or anything you need.

Maybe for future projects ;)

You may close this after reading. Otherwise , leave it open to track progress.

Cheers

**Comment by Wikiki** [comment]
Hi, 

I did use it first but I had issues with the generated build so I get back to webpack.

Thanks for all your help.
Can you please join me on discord at https://discord.gg/8JGj9m3 to discuss about the dateparse issue ?
