### ISSUE TITLE
Propblem with dates.

### ISSUE THREAD

**Issue by sertlab** [Wikiki/bulma-calendar#80]
After the update you ve done yesteday unfortunatelly there is still a small bug.
If you select a date of the CURRENT month, then the selected date is one month later.
For example now is 22/06/18 (im using dd-mm-yy) so if you select 25-06-18 it will give you back 25-07-18.
This problem exists only for current month selected dates.
All other cases works fine.

P.S thank you for this wonderfull calendar.

**Comment by Wikiki** [comment]
Hi,

thanks.

It's an already known bug.
I'll release the fix in few minutes
