### ISSUE TITLE
Feature Request: Date Range Picker

### ISSUE THREAD

**Issue by tolawho** [Wikiki/bulma-calendar#83]

**Comment by Kibouo** [comment]
It's being featured as the 1st item on the [webpage](https://wikiki.github.io/components/calendar/), so I thought it'd be available. Can't find anything in docs or source code.

Would be very useful!

**Comment by fanomena** [comment]
#

**Comment by Wikiki** [comment]
I'm currently working on the documentation.
It should be done around sunday
