### ISSUE TITLE
SelectedValue Angular.io 

### ISSUE THREAD

**Issue by JorgeChibante** [Wikiki/bulma-calendar#88]
Hello, 

I am trying to use the Bulma Calendar on a angular project. I have been able to create the component and attach it to a input however I cannot seem to be able to make it work with reactiveforms. 
I set the formControlName property on the input but the typescript never seems to get the changes I make.

The other way I tried to do this is trying to define a function to handle the select of the calendar component but I also cannot seem to make it work. Whenever I change the value on the component I get a undefined error.

I was wondering if anyone has been able to use the calendar and angular together. Anyone has any example of code any snippet on how to make this work? Eventually any snippet to handle the selectedValue event or something like that. I think I can make it work.
If not can anyone point me in the right direction on how to use the component?

Thank you for your help.

**Comment by Wikiki** [comment]
Hi,

Extensions now includes a more features events management so you just have to call

instance.on('datepicker:date:selected', function(datePicker){});


to react to an event. Each event send the datePicker instance so you are able to retrieve date.

Available events are following:
• datepicker:ready : When initialization is done
• datepicker:rendered : When all days are rendered
• datepicker:show : When datepicker is opened
• datepicker:hide : When datepicker is cloesed
• datepicker 📅 selected : When user has clicked on a date

**Comment by JorgeChibante** [comment]
@Wikiki Thank you for the quick reply, I believe I tried to do that but I always get an undefined error.
I tried to do:

`var picker = bulmaCalendar.attach(#datepicker);`

passing in the options I want and then I tried to do as you suggest:

`picker.on('datepicker:date:selected', function(datePicker){});`

but the error still remains. I always get an undefined error, I cannot seem to figure out why.

**Comment by Wikiki** [comment]
Be careful....<code>.attach()</code> method returns an array

**Comment by JorgeChibante** [comment]
I dont have the code where I tried to call the on method because it never worked, but this is where i create the component.

`    var pickers = bulmaCalendar.attach('#formDatePicker',{
      closeOnOverlayClick: true,
      overlay: true,
      minDate: '2018-01-01',
      maxDate: '2018-12-31'
    })`

I have tried to do 
`pickers[0].on(....)`
`pickers.on()...` --> Clearly wrong

I even tried doing a foreach on the pickers variable and do the on() on each instance but nothing seems to work.
I have the idea doing `pickers[0].on(...)` should be working but it is not.

**Comment by JorgeChibante** [comment]
So as an update, in hopes that someone can help me, this is the output from the console whenever I try to listen to events on the calendar.

![console](https://user-images.githubusercontent.com/10546083/42474675-41e22e16-83c0-11e8-8559-f38caf56b541.PNG)

and this is the code that triggers that error.

`  ngAfterViewInit(): void {
    var pickers = bulmaCalendar.attach('#formDatePicker', {
      closeOnOverlayClick: true,
      overlay: true,
      minDate: '2018-01-01',
      maxDate: '2018-12-31',
    });
    console.log(pickers);
    pickers[0].on('datepicker:date:selected', function(datePicker){
      console.log("changed");
    });
  }`

This is the html:

`<input id="formDatePicker" class="input control has-icons-left has-icons-right" formControlName="eventDate">`

The console log works as you can see but the event doesnt. I also dont have that much experience with javascript so I may be doing things wrong.

**Comment by JorgeChibante** [comment]
Do you have any working example? I am trying now to do this outside of angular and the error still remains.
I always have an undefined error.

**Comment by Wikiki** [comment]
Hi,

your issue is due to the use of a timeout to instanciate calendars (it has been set to fix an issue with react).
To get it work you have to use the following ccode:
```javascript
var calendars = bulmaCalendar.attach('#datepickerDemo');
    window.setTimeout(function() {
      [].forEach.call(calendars, function(calendar) {
      calendar.on('datepicker:date:selected', function(datePicker) {
         // Your work
      });
    })}, 100);
```

**Comment by Wikiki** [comment]
I'll have to check with someone if the timeout still required with react.

**Comment by Wikiki** [comment]
Hi,

the setTimeout has been removed you should now have access to the instances directly after calling <code>.attach()</code> method.
