### ISSUE TITLE
with Vuejs, I need to double-click the input date to open the instance

### ISSUE THREAD

**Issue by alvindimla** [Wikiki/bulma-calendar#91]
the first click creates the instances, but you will need another click to actually show them

**Comment by giolvani** [comment]
It works to me with VueJs. Show us your code or tell when you attach bulmaCalendar.

**Comment by alvindimla** [comment]
I tried to use the attach method on the created() life cycle. But its not working. I even tried to use it when opening the modal where the input date is.

**Comment by megapctr** [comment]
@alvindimla attach it in the `mounted` hook, you don't have a node at `created` yet.
And if you're rendering the input conditionally (e.g. within `v-if` in your component), wait for `this.$nextTick()` after opening the modal. Opening the modal only changes your component's state, render happens afterwards.

**Comment by Wikiki** [comment]
Hi,

I'm currently working on the next release and rewriting documentation. Could someone using Vue.js create a light step by step guide to integrate the component into a VueJs application ? So I'll be able to include it into the documentation directly

**Comment by megapctr** [comment]
Haha, I just did that on #96

**Comment by Wikiki** [comment]
Thanks a lot :-)

**Comment by Wikiki** [comment]
You can call <code>.value()</code> method to get the value or simply read the value property of your input with JavaScript

**Comment by megapctr** [comment]
@alvindimla you can add event listeners on the calendar instance. Maybe this example will help https://codepen.io/megapctr/pen/BOJqNQ

**Comment by alvindimla** [comment]
Thanks guys, it worked well. I've added a few css codes to the index.html to match the style.

Thank you!

**Comment by VietVH10** [comment]
> @alvindimla you can add event listeners on the calendar instance. Maybe this example will help https://codepen.io/megapctr/pen/BOJqNQ

Hi @megapctr I have the issue with it. Also the data appear on the screen was change. But the v-model data not actually change. I set default data equal "17", after selected data so the value not change ??

**Comment by megapctr** [comment]
it seems the API for this package had changed. I managed to get it to work with the following change

```diff
     const calendar = new bulmaCalendar(this.$refs.trigger, {
       startDate: this.date,
     })
-    calendar.on('date:selected', e => (this.date = e.start || null))
+    calendar.on('select', e => (this.date = e.data.date || null))
   },
```
