### ISSUE TITLE
Cannot get value from calendar

### ISSUE THREAD

**Issue by stevensacks** [Wikiki/bulma-calendar#93]
According to the closed issue #50 the calendar supports callbacks, however, it is not working for me.

```javascript
componentDidMount() {
    bulmaCalendar.attach(`#date-picker-${this.props.version.id}`, {
        overlay: true,
        startDate: this.props.version.releaseDate,
        onSelect: this.onDateSelect,
    });
}

onDateSelect = event => {
    console.log('onDateSelect', event);
};
```

My callback function does not get called.

I dug into the source code and there's nothing in there that would call onSelect or any callback by any name you listed above. There's no reference to onSelect, onOpen or onClose in the source code.

The input field onChange doesn't fire, either. And when I check the input element's value using Javascript, it returns its original value, not the updated date, so I can't get the selected date value that way, either.

It's entirely unclear how to actually get the value that the calendar picker selected, and there's nothing in the docs that tells you how to get it.

**Comment by stevensacks** [comment]
Here's a screenshot of me selecting the element after I change the date. As you can see, the inspector still thinks the input's value is the original value, not the changed one. Selecting the input via Javascript also returns the original value.

![screen shot 2018-08-17 at 3 40 21 am](https://user-images.githubusercontent.com/162252/44228140-7a7b4000-a1cf-11e8-9484-3a29ab2aa188.png)

**Comment by stevensacks** [comment]
I tried attaching a listener to the input using raw JavaScript instead of React's onChange.

```javascript
datePickerInputElement.addEventListener('change', e => console.log(e));
```

Nothing.

Short of running a poll every N milliseconds that checks what the element.value is, I don't see how you're able to get what the selected date is. Kinda makes this date picker useless.

**Comment by stevensacks** [comment]
It looks like versions prior to v4 have onSelect in the docs, but v4 does not. Why did you remove the callbacks?

**Comment by stevensacks** [comment]
Ok I found another issue here that says you have to wait 100ms for the calendar instance to be available in the returned array. I waited and was able to add the event listener to it which returns the instance.

I have to say, that’s not a great API and it’s all undocumented which means you have to dig through the issues to find out how to use this component. Bummer.

**Comment by stevensacks** [comment]
I've discovered this is not compatible with react because even if you call destroy() on the instance, it doesn't go away and the next time you click to open, it opens multiple date pickers. Guess I'm gonna have to roll my own. I'll share the component with you when I'm done.

**Comment by Wikiki** [comment]
Hi, the new documentation is on going. The 100ms will be removed in the next release. It was a workaround for a precious version to work with react.
Now the component comes with an event API so you can listen to multiple events like "datepicker:ready", "datepicker:show", "datepicker:date:selected", "datepicker:rendered","datepicker:hide". Each ecent send the datepicker instace then you can get to the selected dateusing the .date property

**Comment by Wikiki** [comment]
Hi,

the setTimeout has been removed you should now have access to the instances directly after calling <code>.attach()</code> method.

**Comment by stevensacks** [comment]
I rolled my own for React. Complete with min/max and range selection support.

Here's the code:
https://gist.github.com/stevensacks/79c60d0f8b1f8bc06b475438f59d687e

I'm using date-fns instead of moment. It's better for a lot of reasons, not least of which is all the helpful utilities for building the calendar, managing min/max, i18n, etc.

I removed the option to have it connected to an input field. It now opens off a Bulma button and it's always a modal dialog. I find this to be more usable.

When it's a single date select, clicking on a date selects that date and closes the dialog (returning the startDate value).

When it's a date range, clicking on dates expands or contracts the date range in what I think is a very usable way. Generally speaking, the endDate is the "anchor" and clicking on dates before the endDate expands or contracts the startDate. If you want to "release" the endDate, click on the startDate twice and it will automatically select the day after the startDate as the new endDate. Same goes for the end date, you click an endDate twice and it jumps the startDate to the day before the endDate.

To make it easier to manage ranges that span over more than a single month, I made it so you can see the startDate and endDate you currently have picked in the nav header, and they are buttons that you click to jump to the month of the startDate or endDate.

Unlike for single date selection, when there's a range the modal dialog has a submit and cancel button.

There's other nice stuff like if you set a startDate earlier than the minDate or endDate later than the maxDate it will automatically set to those thresholds.

Thanks again for making this library. I was able to take your SASS and make a React-specific component out of it. Feel free to leverage any of my code.

**Comment by stevensacks** [comment]
Also, here is the entirety of the Calendar generation code:

https://gist.github.com/stevensacks/79c60d0f8b1f8bc06b475438f59d687e#file-datepickercalendar-js-L37-L70

As you can see, the date-fns library really comes in handy for these kinds of calculations. That and some ES6 Array magic.

**Comment by Wikiki** [comment]
Amazing :-)

I didn't know date-fns.
Do you mind merging your work into my repo to put it available to all the community ?

**Comment by stevensacks** [comment]
I don't have time to change your code, but you're welcome to take mine and modify your own. :)

I will probably release my React component publicly someday soon and I'll give you proper credit and link to your site/repo.
