### ISSUE TITLE
How to use it with Bulma and Vuejs

### ISSUE THREAD

**Issue by Vitorbnc** [Wikiki/bulma-calendar#96]
I have a Vuejs Webpack app with Bulma and Buefy. I couldn't understand how to add bulma-calendar. Could you provide some step-by-step instructions?

**Comment by megapctr** [comment]
It was pretty straightforward for me, but I was also confused by lack of typical installation and import snippets you see everywhere 😅

Here's a simplified example of my component:
```vue
<template>
  <a ref='calendarTrigger'>{{ period.startDate | date }}&ndash;{{ period.endDate | date }}</a>
</template>

<script>
import bulmaCalendar from 'bulma-calendar'

export default {
  mounted() {
    bulmaCalendar.attach(this.$refs.calendarTrigger, {
      startDate: this.period.startDate,
    }),
  },
}
</script>
```

You also need to add calendar styles. If you use sass, you can do it like this:
```scss
@import '~bulma-calendar/dist/css/bulma-calendar.sass';
```

Otherwise, add this css file path somewhere in your build config
```
node_modules/bulma-calendar/dist/css/bulma-calendar.min.css
```

**Comment by Wikiki** [comment]
hi @megapctr ,

I don't know VueJs so could you please describe a little bit more where to put this code ?
So I'll be able to explain this in my documentation.

**Comment by megapctr** [comment]
@Wikiki Does this pen help? https://codepen.io/anon/pen/BOJqNQ?editors=1010

Honestly I had a bit of trobule getting it to work:
- I didn't realize that `attach()` returns an array, even if I've passed a single node
- <s>I'm not sure how to listen to events properly. Here I listen to `date:selected` and pick up the `start` value from the received object. `startDate:selected` didn't work at all for some reason</s> I read the docs again and it looks ok

Also you probably want to remove this odd call which errors :) https://github.com/Wikiki/bulma-calendar/blob/adaf09722665e5a7466be8b24ce5bf8f4298049f/src/js/index.js#L692

**Comment by Vitorbnc** [comment]
That's great! Thanks for the detailed instructions, @megapctr

**Comment by megapctr** [comment]
@Vitorbnc I learned recently that you can use `new bulmaCalendar` instead of `attach` for single nodes. Here's a pen with a full working example: https://codepen.io/anon/pen/BOJqNQ

**Comment by DreaMinder** [comment]
v5.0.5 - events don't work. And your codepen too

**Comment by JeffreyGClark** [comment]
@DreaMinder. I couldn't the listener for "date:selected" to work either. This worked though:

calendar.on("hide", event => (this.setStartDate(event)));
