### ISSUE TITLE
Unable to clear selected date

### ISSUE THREAD

**Issue by mokhosh** [Wikiki/bulma-calendar#99]
I'm using the `overlay` mode and After I select a date, if I decide to clear the selected date and go back to `null` I can't do it. When I click on the `x` button it opens the date picker instead of clearing the selected date.

**Comment by Wikiki** [comment]
Hi,

Do you use an <code>type="date"</code> input element ? I guess the browser send the click to the plugin and so the default behavior is not called. I don't know how to deal with it.

**Comment by mokhosh** [comment]
How about putting a button inside the component for clearing the selected date for now?

**Comment by Wikiki** [comment]
Good idea

**Comment by Wikiki** [comment]
Hi,

I'm working on a new version which will include this functionality added to a lots of bug-fixes
